@startuml evaka-monthly-invoicing
title eVakan kuukausilaskutusprosessi
:Asiakas hakee varhaiskasvatuspaikkaa;
if(Asiakas hyväksyy korkeimman maksun?) then (kyllä)
else (ei)
:Asiakas täyttää tuloselvityksen;
:Talouskoordinaattori (TK) lisää asiakkaalle tulotiedot;
endif
:Syntyy maksupäätösluonnos
(palveluseteliyksikölle arvopäätösluonnos);
:TK tarkastaa puuttuvat
palveluntarpeet ja päämiehet-raportin;
:TK ajaa oman alueensa maksuluonnokset
maksupäätöksiksi kuun viimeinen arkipäivä;
split
    :TK tarkastaa oman alueensa,
    että kaikki maksupäätökset on lähetetty;
    :TK tarkistaa koko kaupungin tyhjät nollapäätökset
    (katkaisee laskutuksen) ja lähettää ne;
    :TK luo laskuluonnokset massana
    kaikille asiakkaille ennen laskujen lähettämistä;
    :TK tekee manuaalisesti hyvitys- ja lisälaskurivit eVakaan;
    :TK siirtää oman alueensa laskut laskutusjärjestelmään;
    :TK tarkistaa oman alueensa laskujen täsmäytyksen;
    kill
split again
    if (Huoltajalla Suomi.fi-viestit käytössä?) then (kyllä)
      :Päätös Suomi.fi-viestinä;
    else (ei)
      if (Hakijalla turvakielto) then (kyllä)
        :TK selvittää turvakiellollisen osoitteen;
      else (ei)
      endif
      :TK lähettää päätöksen maapostissa;
    endif
    kill
end split
@enduml