' SPDX-FileCopyrightText: 2017-2021 City of Espoo
'
' SPDX-License-Identifier: LGPL-2.1-or-later

@startuml evaka-correcting-invoicing
title eVakan laskutuksen korjausprosessi

:Asiakas huomaa virheen maksupäätöksessä tai laskussa;
:Asiakas ottaa yhteyttä talouskoordinaattoriin (TK);
:TK käsittelee korjaustarpeen asiakkaan ja 
tarvittaessa yksikön kanssa;
split
  :Tulotiedot;
  :TK korjaa tiedot;
split again
split
  :Perhekoko;
split again
  :Perheen kokoonpano;
split again
  :Sijoitus tai palveluntarve;
split again
  :Päiväkirjatiedot;
end split
  :Päiväkodin johtaja korjaa tiedot;
end split
:Syntyy uusi maksupäätösluonnos;
:TK luo maksupäätöksen;
split
:TK korjaa laskutuksen käsin laskutusjärjestelmään;
split again
:TK tekee manuaalisesti hyvitys- ja lisälaskurivit eVakaan (jatkuva prosessi);
end split
@enduml