// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package fi.espoo.evaka.vtjclient.soap;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-17T13:59:02.370+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", name = "ISoSoAdapterService60")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00", comments = "Apache CXF 3.3.2")
public interface ISoSoAdapterService60 {

    @WebMethod(operationName = "HenkilonTunnusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/HenkilonTunnusKyselyResponse")
    @RequestWrapper(localName = "HenkilonTunnusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.HenkiloTunnusKyselyReqBody")
    @ResponseWrapper(localName = "HenkilonTunnusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.HenkiloTunnusKyselyResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void henkilonTunnusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<HenkiloTunnusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<HenkiloTunnusKyselyResType> response
    );

    @WebMethod(operationName = "KiinteistonTunnusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/KiinteistonTunnusKyselyResponse")
    @RequestWrapper(localName = "KiinteistonTunnusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.KiinteistoTunnusKyselyReqBody")
    @ResponseWrapper(localName = "KiinteistonTunnusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.KiinteistoTunnusKyselyResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void kiinteistonTunnusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<KiinteistoTunnusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<KiinteistoTunnusKyselyResType> response
    );

    @WebMethod(operationName = "HaeTuotteenSkeema")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/HaeTuotteenSkeemaResponse")
    @RequestWrapper(localName = "HaeTuotteenSkeema", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.TuotteenSkeemaReqBody")
    @ResponseWrapper(localName = "HaeTuotteenSkeemaResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.TuotteenSkeemaResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void haeTuotteenSkeema(
        @WebParam(name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        fi.espoo.evaka.vtjclient.soap.TuotteenSkeemaReqBodyTiedot request,
        @WebParam(mode = WebParam.Mode.OUT, name = "reguest", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<TuotteenSkeemaReqBodyTiedot> reguest,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<TuotteenSkeemaResType> response
    );

    @WebMethod(operationName = "RakennuksenTunnistusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/RakennuksenTunnistusKyselyResponse")
    @RequestWrapper(localName = "RakennuksenTunnistusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.RakennusTunnistusKyselyReqBody")
    @ResponseWrapper(localName = "RakennuksenTunnistusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.RakennusTunnistusKyselyResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void rakennuksenTunnistusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<RakennusTunnistusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<RakennusTunnistusKyselyResType> response
    );

    @WebMethod(operationName = "RakennuksenTunnusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/RakennuksenTunnusKyselyResponse")
    @RequestWrapper(localName = "RakennuksenTunnusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.RakennusTunnusKyselyReqBody")
    @ResponseWrapper(localName = "RakennuksenTunnusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.RakennusTunnusKyselyResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void rakennuksenTunnusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<RakennusTunnusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<RakennusTunnusKyselyResType> response
    );

    @WebMethod(operationName = "KiinteistonTunnistusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/KiinteistonTunnistusKyselyResponse")
    @RequestWrapper(localName = "KiinteistonTunnistusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.KiinteistoTunnistusKyselyReqBody")
    @ResponseWrapper(localName = "KiinteistonTunnistusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.KiinteistoTunnistusKyselyResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void kiinteistonTunnistusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<KiinteistoTunnistusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<KiinteistoTunnistusKyselyResType> response
    );

    @WebMethod(operationName = "HenkilonTunnistusKysely")
    @Action(output = "http://xml.vrk.fi/ws/vtj/vtjkysely/1/ISoSoAdapterService60/HenkilonTunnistusKyselyResponse")
    @RequestWrapper(localName = "HenkilonTunnistusKysely", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.HenkiloTunnistusKyselyReqBody")
    @ResponseWrapper(localName = "HenkilonTunnistusKyselyResponse", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1", className = "fi.espoo.evaka.vtjclient.soap.HenkiloTunnistusKyselyResBody")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.370+03:00")
    public void henkilonTunnistusKysely(
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<HenkiloTunnistusKyselyReqBodyTiedot> request,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
        javax.xml.ws.Holder<HenkiloTunnistusKyselyResType> response
    );
}
