// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package fi.espoo.evaka.vtjclient.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
  * 2019-07-17T13:59:02.406+03:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "SoSoAdapterService60",
                  wsdlLocation = "file:/home/mikko/dev/voltti/evaka-pis-service/src/main/resources/wsdl/service.wsdl",
                  targetNamespace = "http://xml.vrk.fi/ws/vtj/vtjkysely/1")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00", comments = "Apache CXF 3.3.2")
public class SoSoAdapterService60 extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public final static QName SERVICE = new QName("http://xml.vrk.fi/ws/vtj/vtjkysely/1", "SoSoAdapterService60");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public final static QName BasicHttpBindingISoSoAdapterService60 = new QName("http://xml.vrk.fi/ws/vtj/vtjkysely/1", "BasicHttpBinding_ISoSoAdapterService60");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/mikko/dev/voltti/evaka-pis-service/src/main/resources/wsdl/service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoSoAdapterService60.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/mikko/dev/voltti/evaka-pis-service/src/main/resources/wsdl/service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public SoSoAdapterService60(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public SoSoAdapterService60(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public SoSoAdapterService60() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public SoSoAdapterService60(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public SoSoAdapterService60(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public SoSoAdapterService60(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ISoSoAdapterService60
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoSoAdapterService60")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public ISoSoAdapterService60 getBasicHttpBindingISoSoAdapterService60() {
        return super.getPort(BasicHttpBindingISoSoAdapterService60, ISoSoAdapterService60.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoSoAdapterService60
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoSoAdapterService60")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-07-17T13:59:02.406+03:00")
    public ISoSoAdapterService60 getBasicHttpBindingISoSoAdapterService60(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingISoSoAdapterService60, ISoSoAdapterService60.class, features);
    }

}
