// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faCalendarAlt,
  faCaretUp,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faExchangeAlt,
  faExclamation,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFemale,
  faFile,
  faFileAlt,
  faFileCsv,
  faFileImage,
  faFilePdf,
  faFileWord,
  faGavel,
  faHandHolding,
  faHiking,
  faHome,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faStickyNote,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers
} from '@fortawesome/free-solid-svg-icons'
import {
  faFileAlt as farFileAlt,
  faMap as farMap,
  faStickyNote as farStickyNote,
  faUser as farUser
} from '@fortawesome/free-regular-svg-icons'
import { IconSet } from '.'

const icons: IconSet = {
  faAbacus: faPercentage,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt: faEllipsisV,
  faEye,
  faEyeSlash,
  faExchange: faExchangeAlt,
  faExclamation,
  faExclamationTriangle,
  faExternalLink: faExternalLinkAlt,
  faFemale,
  faFile,
  faFileAlt,
  faFileImage,
  faFilePdf,
  faFileSpreadsheet: faFileCsv,
  faFileWord,
  faGavel,
  faHandHolding,
  faHiking,
  faHomeAlt: faHome,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit: faMoneyCheck,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignIn: faSignInAlt,
  faSignOut: faSignOutAlt,
  faStickyNote,
  farStickyNote,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers,
  farFileAlt,
  farGavel: faGavel,
  farMap,
  fasCaretUp: faCaretUp,
  fasCheckCircle: faCheckCircle,
  fasChevronDown: faChevronDown,
  fasChevronUp: faChevronUp,
  fasExclamationTriangle: faExclamationTriangle,
  fasInfo: faInfo,
  fasMapMarkerAlt: faMapMarkerAlt,
  fasArrowDown: faArrowDown,
  fasArrowUp: faArrowUp,
  farUser
}

export default icons
