// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

// units
export const UPDATE_UNITS = 'UPDATE_UNITS'
export const UPDATE_ACTIVE_TERM = 'UPDATE_ACTIVE_TERMS'
export const SELECT_TERM = 'SELECT_TERM'
export const SET_INITIAL_TERM = 'SET_INITIAL_TERM'
export const LOAD_APPLICATION_UNITS = 'LOAD_APPLICATION_UNITS'

// filters
export const APPLY_ADDRESS_FILTER = 'APPLY_ADDRESS_FILTER'
export const CLEAR_ADDRESS_FILTER = 'CLEAR_ADDRESS_FILTER'
export const APPLY_LANGUAGE_FILTER = 'APPLY_LANGUAGE_FILTER'
export const APPLY_DAYCARE_FILTER = 'APPLY_DAYCARE_FILTER'
export const DISABLE_FILTERS = 'DISABLE_FILTERS'
export const ENABLE_FILTERS = 'ENABLE_FILTERS'
export const INIT_FILTERS = 'INIT_FILTERS'

// addresses
export const UPDATE_ADDRESSES = 'UPDATE_ADDRESSES'
export const CLEAR_ADDRESSES = 'CLEAR_ADDRESSES'
export const SELECT_LOCATION = 'SELECT_LOCATION'
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION'
export const CLEAR_DESTINATION = 'CLEAR_DESTINATION'
export const SELECT_DESTINATION = 'SELECT_DESTINATION'
export const INIT_ADDRESSES = 'INIT_ADDRESSES'
export const DISABLE_DESTINATION = 'DISABLE_DESTINATION'
export const ENABLE_DESTINATION = 'ENABLE_DESTINATION'

// map
export const MAP_API_LOADED = 'MAP_API_LOADED'

// forms
export const UPDATE_FORM = 'UPDATE_FORM'
export const UPDATE_DAYCARE_FORM = 'UPDATE_DAYCARE_FORM'
export const CLEAR_FORM = 'CLEAR_FORM'
export const CLEAR_DAYCARE_FORM = 'CLEAR_DAYCARE_FORM'
export const LOAD_APPLICATION_FORM = 'LOAD_APPLICATION_FORM'
export const LOAD_DAYCARE_APPLICATION_FORM = 'LOAD_DAYCARE_APPLICATION_FORM'
export const REVERT_APPLICATION_FORM = 'REVERT_APPLICATION_FORM'
export const ADD_CHILD = 'ADD_CHILD'
export const REMOVE_CHILD = 'REMOVE_CHILD'
export const UPDATE_CHILD = 'UPDATE_CHILD'
export const REMOVE_CHILDREN = 'REMOVE_CHILDREN'

// validations
export const UPDATE_VALIDATION = 'UPDATE_VALIDATION'
export const VALIDATE_ALL = 'VALIDATE_ALL'
export const REMOVE_VALIDATION = 'REMOVE_VALIDATION'

// Form section
export const TOGGLE_SECTION = 'TOGGLE_SECTION'

// files
export const ADD_URGENCY_FILE = 'ADD_URGENCY_FILE'
export const UPDATE_URGENCY_FILE = 'UPDATE_URGENCY_FILE'
export const DELETE_URGENCY_FILE = 'DELETE_URGENCY_FILE'
export const ADD_EXTENDED_CARE_FILE = 'ADD_EXTENDED_CARE_FILE'
export const UPDATE_EXTENDED_CARE_FILE = 'UPDATE_EXTENDED_CARE_FILE'
export const DELETE_EXTENDED_CARE_FILE = 'DELETE_EXTENDED_CARE_FILE'

// applications
export const START_LOADING_APPLICATIONS = 'START_LOADING_APPLICATIONS'
export const LOAD_APPLICATIONS = 'LOAD_APPLICATIONS'
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION'
export const SAVE_APPLICATION = 'SAVE_APPLICATION'
export const NEW_APPLICATION = 'NEW_APPLICATION'

// decisions
export const START_LOADING_DECISIONS = 'START_LOADING_DECISIONS'
export const LOAD_DECISIONS = 'LOAD_DECISIONS'

// translations
export const ADD_TRANSLATIONS = 'ADD_TRANSLATIONS'
