export type IncomeSource = 'INCOMES_REGISTER' | 'ATTACHMENTS'

export const otherIncome = [
  'PENSION',
  'ADULT_EDUCATION_ALLOWANCE',
  'SICKNESS_ALLOWANCE',
  'PARENTAL_ALLOWANCE',
  'HOME_CARE_ALLOWANCE',
  'FLEXIBLE_AND_PARTIAL_HOME_CARE_ALLOWANCE',
  'ALIMONY',
  'INTEREST_AND_INVESTMENT_INCOME',
  'RENTAL_INCOME'
] as const

export type OtherIncome = typeof otherIncome[number]

export const attachmentType = [
  'PENSION',
  'ADULT_EDUCATION_ALLOWANCE',
  'SICKNESS_ALLOWANCE',
  'PARENTAL_ALLOWANCE',
  'HOME_CARE_ALLOWANCE',
  'FLEXIBLE_AND_PARTIAL_HOME_CARE_ALLOWANCE',
  'ALIMONY',
  'ALIMONY_PAYOUT',
  'INTEREST_AND_INVESTMENT_INCOME',
  'RENTAL_INCOME',
  'PAYSLIP',
  'STARTUP_GRANT',
  'ACCOUNTANT_REPORT',
  'PROFIT_AND_LOSS_STATEMENT',
  'PROOF_OF_STUDIES'
] as const

export type AttachmentType = typeof attachmentType[number]
