# SPDX-FileCopyrightText: 2021 City of Oulu
#
# SPDX-License-Identifier: LGPL-2.1-or-later
heading.1=PÄÄTÖS
heading.2=varhaiskasvatuksen palvelusetelin arvosta
heading.3=Salassa pidettävä JulkL 24.1 § 23 kohta
heading.4=Päätöspvm {0}
pageNumber=Sivu {0}
decisionNumber=Päätös nro
text.title=Päätös varhaiskasvatuksen palvelusetelin arvosta
text.feeAlterationType.DISCOUNT=Alennus
text.feeAlterationType.INCREASE=Korotus
text.feeAlterationType.RELIEF=Huojennus
heading.relief.1=PÄÄTÖS varhaiskasvatusmaksun
heading.relief.2=huojennuksesta
text.relief.title=Päätös varhaiskasvatusmaksun huojennuksesta
text.relief.accepted=Hakemuksenne hyväksytään.
text.relief.partlyAccepted=Hakemuksenne hyväksytään osittain.
text.relief.rejected=Hakemuksenne hylätään.
text.relief.decision=Varhaiskasvatuksen omavastuuosuus on {0} euroa alkaen {1} edellytyksellä, että annetuissa \
  tiedoissa ei tapahdu muutosta. Varhaiskasvatusmaksun huojennus perustuu oheisen liitteen mukaiseen \
  maksuvaralaskelmaan.
decision.details.child=Lapsellenne {0} {1} ({2}) on myönnetty palveluseteli {3} alkaen.
decision.details.unitTitle=Lapsenne varhaiskasvatuspaikka on {0}.
decision.details.customerFeeInfo=\
  <h2>Palvelusetelin arvo</h2>\
  <p>Kunta myöntää asiakkaalle tulosidonnaisen palvelusetelin. Palvelusetelin arvossa on huomioitu asiakkaan toimittamien tulotietojen perusteella laskettu varhaiskasvatuksen asiakasmaksulain 11 §:n mukainen osuus. Palveluntuottaja laskuttaa varhaiskasvatuspaikan hinnan ja kunnan myöntämän tulosidonnaisen palvelusetelin arvon välisen erotuksen asiakkaan kanssa tehdyn palvelusopimuksen mukaisesti.</p>\
  <p>Mikäli teillä on palvelusetelin arvoon tai tuloihin liittyvää kysyttävää, ottakaa yhteyttä varhaiskasvatuksen asiakasmaksutiimiin (p. 08 558 45300 ti-to 9.00-12.00).</p>
decision.details.incomeChanges=\
  <p>Mikäli olette saaneet päätöksen puutteellisilla tulotiedoilla, toimittakaa tuloselvitykset tai hyväksykää korkein maksu eVaka-palvelussa.</p>\
  <p>Jos perheen bruttotuloissa tapahtuu olennaisia (+/-10 %) muutoksia, on uusi tuloselvitys tehtävä välittömästi.</p>
decision.legalInstructions=\
  <h2>Sovelletut oikeusohjeet</h2>\
  <ul><li>Laki varhaiskasvatuksen asiakasmaksuista (1503/2016)</li>\
  <li>Laki varhaiskasvatuksen palvelusetelistä (1048/2025)</li>\
  <li>Oulun kaupungin varhaiskasvatuksen palvelusetelisääntökirja</li></ul>
decision.sentDate=Päätös- ja lähetyspäivä
decision.decisionMethodTitle=Tiedoksiantotapa:
decision.decisionMethod.sent=Lähetetty
decision.approver.prefix=Päätöksentekijä: 
decision.approver.additionalInfo=(allekirjoitettu koneellisesti)
decision.approver.title=Asiakaspalvelusihteeri
decision.approver.unit=
decision.approver.details=p. 08 558 45300 (valitse numero 2)
decision.inform.guardians=Tiedoksi: Huoltajat
decision.instructionsForCalculation=\
  <h2>Laskennassa huomioon otetut tulot:</h2>
decision.income.maxFeeAccepted=maksimi
decision.income.notAvailable=tulotietoja ei toimitettu
decision.serviceNeed=Palveluntarve
decision.familySize=Perhekoko
decision.baseValue=Palvelusetelin enimmäisarvo
decision.coPayment=Omavastuuosuus
decision.amountOfVoucherForProvider=Palveluntuottajalle maksettava palveluseteli
decision.currency=€
text.placementType.daycare=Varhaiskasvatus
text.placementType.preschool=Esiopetus ja liittyvä varhaiskasvatus
text.placementType.preparatory=Esiopetus ja valmistava opetus
text.reference=Lisätietoja maksun määräytymisestä löytyy Oulun kaupungin verkkosivuilta:
text.referenceUrl=https://www.ouka.fi/oulu/paivahoito-ja-esiopetus/paivahoitomaksut
text.referenceUrlText=Varhaiskasvatuksen asiakasmaksut