# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later
header.1=ILMOITUS
header.2=kerhopaikasta
decision.title=Ilmoitus kerhopaikasta
decision.placement.unit=Kerhopaikka
decision.unitsupervisor=Kerhopaikan esihenkilö
decision.unitmanagertitle=Päiväkodin johtaja
decision.instructions=\
  <p>Kerhopaikka tulee vastaanottaa tai hylätä viipymättä, viimeistään kahden viikon kuluessa tämän ilmoituksen saamisesta. \
  Kerhopaikan voi hyväksyä / hylätä sähköisesti osoitteessa <a href="https://varhaiskasvatus.tampere.fi">varhaiskasvatus.tampere.fi</a> (edellyttää tunnistautumista) tai ottamalla yhteyttä päiväkodin johtajaan. \
  Jos tarjottua kerhopaikkaa ei ota vastaan, uuden kerhopaikan voi saada vain tekemällä uuden hakemuksen.</p>
