import {
  faCircle as fasCircle,
  faExclamationCircle as fasExclamationCircle,
  faHome as fasHome,
  faInfoCircle as fasInfoCircle,
  faMapMarkerAlt as fasMapMarkerAlt
} from '@fortawesome/pro-solid-svg-icons'

import {
  faAngleRight as farAngleRight,
  faAt as farAt,
  faCalendar as farCalendar,
  faCalendarAlt as farCalendarAlt,
  faCheck as farCheck,
  faFileAlt as farFileAlt,
  faFilePdf as farFilePdf,
  faGavel as farGavel,
  faHands as farHands,
  faHome as farHome,
  faIdCard as farIdCard,
  faLevelUp as farLevelUp,
  faList as farList,
  faMap as farMap,
  faMobile as farMobile,
  faMobileAlt as farMobileAlt,
  faPencil as farPencil,
  faPlus as farPlus,
  faSearch as farSearch,
  faSpinner as farSpinner,
  faTrash as farTrash,
  faUser as farUser
} from '@fortawesome/pro-regular-svg-icons'

import {
  faAngleDown as falAngleDown,
  faAngleUp as falAngleUp,
  faArrowRight as falArrowRight,
  faCalendar as falCalendar,
  faCheck as falCheck,
  faChild as falChild,
  faClock as falClock,
  faEnvelope as falEnvelope,
  faEuroSign as falEuroSign,
  faExclamation as falExclamation,
  faExclamationTriangle as falExclamationTriangle,
  faFile as falFile,
  faGavel as falGavel,
  faHands as falHands,
  faInfo as falInfo,
  faLink as falLink,
  faMapMarkerAlt as falMapMarkerAlt,
  faPlay as falPlay,
  faSignIn as falSignIn,
  faSignOut as falSignOut,
  faStar as falStar,
  faTimes as falTimes,
  faTrash as falTrash,
  faUser as falUser,
  faUsers as falUsers
} from '@fortawesome/pro-light-svg-icons'

import { IconSet } from '../icon-set'

const icons: IconSet = {
  fasCircle,
  fasExclamationCircle,
  fasHome,
  fasInfoCircle,
  fasMapMarkerAlt,
  farAngleRight,
  farAt,
  farCalendar,
  farCalendarAlt,
  farCheck,
  farFileAlt,
  farFilePdf,
  farGavel,
  farHands,
  farHome,
  farIdCard,
  farLevelUp,
  farList,
  farMap,
  farMobile,
  farMobileAlt,
  farPencil,
  farPlus,
  farSearch,
  farSpinner,
  farTrash,
  farUser,
  falAngleDown,
  falAngleUp,
  falArrowRight,
  falCalendar,
  falCheck,
  falChild,
  falClock,
  falEnvelope,
  falEuroSign,
  falExclamation,
  falExclamationTriangle,
  falFile,
  falGavel,
  falHands,
  falInfo,
  falLink,
  falMapMarkerAlt,
  falPlay,
  falSignIn,
  falSignOut,
  falStar,
  falTimes,
  falTrash,
  falUser,
  falUsers
}

export default icons
