-- References to person table that should be ON DELETE RESTRICT
ALTER TABLE application DROP CONSTRAINT application_other_guardian_fkey;
ALTER TABLE application ADD CONSTRAINT application_other_guardian_fkey FOREIGN KEY (other_guardian_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE application DROP CONSTRAINT application_guardian_fkey;
ALTER TABLE application ADD CONSTRAINT application_guardian_fkey FOREIGN KEY (guardian_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE application DROP CONSTRAINT application_child_fkey;
ALTER TABLE application ADD CONSTRAINT application_child_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE fee_decision DROP CONSTRAINT new_fee_decision_partner_id_fkey;
ALTER TABLE fee_decision ADD CONSTRAINT new_fee_decision_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE fee_decision DROP CONSTRAINT new_fee_decision_head_of_family_id_fkey;
ALTER TABLE fee_decision ADD CONSTRAINT new_fee_decision_head_of_family_id_fkey FOREIGN KEY (head_of_family_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE fee_decision_child DROP CONSTRAINT new_fee_decision_child_child_id_fkey;
ALTER TABLE fee_decision_child ADD CONSTRAINT new_fee_decision_child_child_id_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE voucher_value_decision DROP CONSTRAINT voucher_value_decision_child_fkey;
ALTER TABLE voucher_value_decision ADD CONSTRAINT voucher_value_decision_child_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE voucher_value_decision DROP CONSTRAINT fk$head_of_family;
ALTER TABLE voucher_value_decision ADD CONSTRAINT fk$head_of_family FOREIGN KEY (head_of_family_id) REFERENCES person(id) ON DELETE RESTRICT;
ALTER TABLE voucher_value_decision DROP CONSTRAINT fk$partner;
ALTER TABLE voucher_value_decision ADD CONSTRAINT fk$partner FOREIGN KEY (partner_id) REFERENCES person(id) ON DELETE RESTRICT;

-- References to person table that should be ON DELETE CASCADE
ALTER TABLE child DROP CONSTRAINT fk$child_id_person_id;
ALTER TABLE child ADD CONSTRAINT fk$child_id_person_id FOREIGN KEY (id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE fee_alteration DROP CONSTRAINT fk$person_id;
ALTER TABLE fee_alteration ADD CONSTRAINT fk$person_id FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE old_fee_decision DROP CONSTRAINT fk$head_of_family;
ALTER TABLE old_fee_decision ADD CONSTRAINT fk$head_of_family FOREIGN KEY (head_of_family) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE old_fee_decision DROP CONSTRAINT fk$partner;
ALTER TABLE old_fee_decision ADD CONSTRAINT fk$partner FOREIGN KEY (partner) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE old_fee_decision_part DROP CONSTRAINT fk$child;
ALTER TABLE old_fee_decision_part ADD CONSTRAINT fk$child FOREIGN KEY (child) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE fridge_child DROP CONSTRAINT fridge_child_head_of_child_fkey;
ALTER TABLE fridge_child ADD CONSTRAINT fridge_child_head_of_child_fkey FOREIGN KEY (head_of_child) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE fridge_child DROP CONSTRAINT fridge_child_child_id_fkey;
ALTER TABLE fridge_child ADD CONSTRAINT fridge_child_child_id_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE fridge_partner DROP CONSTRAINT fridge_partner_person_id_fkey;
ALTER TABLE fridge_partner ADD CONSTRAINT fridge_partner_person_id_fkey FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE guardian DROP CONSTRAINT fk$child_id;
ALTER TABLE guardian ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE guardian DROP CONSTRAINT fk$guardian_id;
ALTER TABLE guardian ADD CONSTRAINT fk$guardian_id FOREIGN KEY (guardian_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE income DROP CONSTRAINT fk$person_id;
ALTER TABLE income ADD CONSTRAINT fk$person_id FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE invoice DROP CONSTRAINT fk$head_of_family;
ALTER TABLE invoice ADD CONSTRAINT fk$head_of_family FOREIGN KEY (head_of_family) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE invoice_row DROP CONSTRAINT fk$child_id;
ALTER TABLE invoice_row ADD CONSTRAINT fk$child_id FOREIGN KEY (child) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE varda_child DROP CONSTRAINT fk$person_id;
ALTER TABLE varda_child ADD CONSTRAINT fk$person_id FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE attachment DROP CONSTRAINT attachment_uploaded_by_person_fkey;
ALTER TABLE attachment ADD CONSTRAINT attachment_uploaded_by_person_fkey FOREIGN KEY (uploaded_by_person) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE daycare_daily_note DROP CONSTRAINT daycare_daily_note_child_fkey;
ALTER TABLE daycare_daily_note ADD CONSTRAINT daycare_daily_note_child_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE messaging_blocklist DROP CONSTRAINT messaging_blocklist_child_id_fkey;
ALTER TABLE messaging_blocklist ADD CONSTRAINT messaging_blocklist_child_id_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE messaging_blocklist DROP CONSTRAINT messaging_blocklist_blocked_recipient_fkey;
ALTER TABLE messaging_blocklist ADD CONSTRAINT messaging_blocklist_blocked_recipient_fkey FOREIGN KEY (blocked_recipient) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE backup_pickup DROP CONSTRAINT backup_pickup_child_fkey;
ALTER TABLE backup_pickup ADD CONSTRAINT backup_pickup_child_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE family_contact DROP CONSTRAINT family_contact_child_id_fkey;
ALTER TABLE family_contact ADD CONSTRAINT family_contact_child_id_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE family_contact DROP CONSTRAINT family_contact_contact_person_id_fkey;
ALTER TABLE family_contact ADD CONSTRAINT family_contact_contact_person_id_fkey FOREIGN KEY (contact_person_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE daily_service_time DROP CONSTRAINT daily_service_time_child_id_fkey;
ALTER TABLE daily_service_time ADD CONSTRAINT daily_service_time_child_id_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE message_account DROP CONSTRAINT message_account_person_id_fkey;
ALTER TABLE message_account ADD CONSTRAINT message_account_person_id_fkey FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE child_images DROP CONSTRAINT child_images_child_id_fkey;
ALTER TABLE child_images ADD CONSTRAINT child_images_child_id_fkey FOREIGN KEY (child_id) REFERENCES person(id) ON DELETE CASCADE;
ALTER TABLE varda_service_need DROP CONSTRAINT varda_service_need_evaka_child_id_fkey;
ALTER TABLE varda_service_need ADD CONSTRAINT varda_service_need_evaka_child_id_fkey FOREIGN KEY (evaka_child_id) REFERENCES person(id) ON DELETE CASCADE;

-- References to child table that should be ON DELETE RESTRICT
ALTER TABLE placement DROP CONSTRAINT fk$child_id;
ALTER TABLE placement ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE RESTRICT;
ALTER TABLE absence DROP CONSTRAINT fk$child_id;
ALTER TABLE absence ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE RESTRICT;
ALTER TABLE child_attendance DROP CONSTRAINT child_attendance_child_id_fkey;
ALTER TABLE child_attendance ADD CONSTRAINT child_attendance_child_id_fkey FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE RESTRICT;

-- References to child table that should be ON DELETE CASCADE
ALTER TABLE assistance_need DROP CONSTRAINT fk$child_id;
ALTER TABLE assistance_need ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE CASCADE;
ALTER TABLE assistance_action DROP CONSTRAINT fk$child_id;
ALTER TABLE assistance_action ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE CASCADE;
ALTER TABLE backup_care DROP CONSTRAINT fk$child_id;
ALTER TABLE backup_care ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE CASCADE;
ALTER TABLE koski_study_right DROP CONSTRAINT fk$child_id;
ALTER TABLE koski_study_right ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE CASCADE;
ALTER TABLE old_service_need DROP CONSTRAINT fk$child_id;
ALTER TABLE old_service_need ADD CONSTRAINT fk$child_id FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE CASCADE;
