ALTER TYPE placement_type ADD VALUE IF NOT EXISTS 'PRESCHOOL_DAYCARE_ONLY' AFTER 'PRESCHOOL_DAYCARE';
ALTER TYPE placement_type ADD VALUE IF NOT EXISTS 'PREPARATORY_DAYCARE_ONLY' AFTER 'PREPARATORY_DAYCARE';
