ALTER TABLE document_template ADD COLUMN placement_types placement_type[];

UPDATE document_template
SET placement_types = '{CLUB, DAYCARE, DAYCARE_PART_TIME, DAYCARE_FIVE_YEAR_OLDS, DAYCARE_PART_TIME_FIVE_YEAR_OLDS, PRESCHOOL, PRESCHOOL_DAYCARE, PRESCHOOL_DAYCARE_ONLY, PRESCHOOL_CLUB, PREPARATORY, PREPARATORY_DAYCARE, PREPARATORY_DAYCARE_ONLY, TEMPORARY_DAYCARE, TEMPORARY_DAYCARE_PART_DAY, SCHOOL_SHIFT_CARE}'::placement_type[];

ALTER TABLE document_template ALTER COLUMN placement_types SET NOT NULL;

ALTER TYPE document_template_type ADD VALUE 'OTHER';
