// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faAt,
  faCalendar,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faCircle,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faExchangeAlt,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faFemale,
  faFile,
  faFileAlt,
  faFileCsv,
  faFilePdf,
  faGavel,
  faHandHolding,
  faHands,
  faHiking,
  faHome,
  faHourglassEnd,
  faHourglassStart,
  faIdCard,
  faInfo,
  faInfoCircle,
  faLevelUpAlt,
  faLink,
  faList,
  faMap,
  faMapMarkerAlt,
  faMeh,
  faMobileAlt,
  faMoneyCheck,
  faPen,
  faPencilAlt,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSpinner,
  faStar,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers
} from '@fortawesome/free-solid-svg-icons'
import { IconDefinition, IconName, IconPrefix } from '@fortawesome/fontawesome-svg-core'
import { IconSet } from './types'

/**
 * Helper function for converting the free solid icon set to be interpreted as
 * the different pro variations by vue-fontawesome
 */
const convert = (
  icon: IconDefinition,
  prefix: IconPrefix,
  iconName: IconName = icon.iconName
): IconDefinition => ({
  ...icon,
  prefix,
  iconName
})

const icons: IconSet = {
  faAbacus: convert(faPercentage, 'fal', 'abacus'),
  faAngleDown: convert(faAngleDown, 'fal'),
  faAngleLeft: convert(faAngleLeft, 'fal'),
  faAngleRight: convert(faAngleRight, 'fal'),
  faArrowDown: convert(faArrowDown, 'fal'),
  faArrowLeft: convert(faArrowLeft, 'fal'),
  faArrowRight: convert(faArrowRight, 'fal'),
  faAngleUp: convert(faAngleUp, 'fal'),
  faArrowUp: convert(faArrowUp, 'fal'),
  faCalendar: convert(faCalendar, 'fal'),
  faCalendarAlt: convert(faCalendarAlt, 'fal'),
  faCheck: convert(faCheck, 'fal'),
  faCheckCircle: convert(faCheckCircle, 'fal'),
  faChevronDown: convert(faChevronDown, 'fal'),
  faChevronLeft: convert(faChevronLeft, 'fal'),
  faChevronRight: convert(faChevronRight, 'fal'),
  faChevronUp: convert(faChevronUp, 'fal'),
  faChild: convert(faChild, 'fal'),
  faClock: convert(faClock, 'fal'),
  faCoins: convert(faCoins, 'fal'),
  faCopy: convert(faCopy, 'fal'),
  faDatabase: convert(faDatabase, 'fal'),
  faDiagnoses: convert(faDiagnoses, 'fal'),
  faEnvelope: convert(faEnvelope, 'fal'),
  faEuroSign: convert(faEuroSign, 'fal'),
  faEllipsisVAlt: convert(faEllipsisV, 'fal', 'ellipsis-v-alt'),
  faEye: convert(faEye, 'fal'),
  faEyeSlash: convert(faEyeSlash, 'fal'),
  faExchange: convert(faExchangeAlt, 'fal', 'exchange'),
  faExclamation: convert(faExclamation, 'fal'),
  faExclamationTriangle: convert(faExclamationTriangle, 'fal'),
  faFemale: convert(faFemale, 'fal'),
  faFile: convert(faFile, 'fal'),
  faFileAlt: convert(faFileAlt, 'fal'),
  faFilePdf: convert(faFilePdf, 'fal'),
  faFileSpreadsheet: convert(faFileCsv, 'fal', 'file-spreadsheet'),
  faGavel: convert(faGavel, 'fal'),
  faHandHolding: convert(faHandHolding, 'fal'),
  faHands: convert(faHands, 'fal'),
  faHiking: convert(faHiking, 'fal'),
  faHomeAlt: convert(faHome, 'fal'),
  faHourglassEnd: convert(faHourglassEnd, 'fal'),
  faHourglassStart: convert(faHourglassStart, 'fal'),
  faInfo: convert(faInfo, 'fal'),
  faInfoCircle: convert(faInfoCircle, 'fal'),
  faLink: convert(faLink, 'fal'),
  faMapMarkerAlt: convert(faMapMarkerAlt, 'fal'),
  faMeh: convert(faMeh, 'fal'),
  faMoneyCheck: convert(faMoneyCheck, 'fal'),
  faMoneyCheckEdit: convert(faMoneyCheck, 'fal', 'money-check-edit'),
  faPen: convert(faPen, 'fal'),
  faPercentage: convert(faPercentage, 'fal'),
  faPlay: convert(faPlay, 'fal'),
  faPlus: convert(faPlus, 'fal'),
  faPlusCircle: convert(faPlusCircle, 'fal'),
  faQuestion: convert(faQuestion, 'fal'),
  faQuestionCircle: convert(faQuestionCircle, 'fal'),
  faSearch: convert(faSearch, 'fal'),
  faSignIn: convert(faSignInAlt, 'fal', 'sign-in'),
  faSignOut: convert(faSignOutAlt, 'fal', 'sign-out'),
  faStar: convert(faStar, 'fal'),
  faSync: convert(faSync, 'fal'),
  faTimes: convert(faTimes, 'fal'),
  faTrash: convert(faTrash, 'fal'),
  faUndo: convert(faUndo, 'fal'),
  faUser: convert(faUser, 'fal'),
  faUserAltSlash: convert(faUserAltSlash, 'fal'),
  faUserFriends: convert(faUserFriends, 'fal'),
  faUsers: convert(faUsers, 'fal'),
  farAngleRight: convert(faAngleRight, 'far'),
  farAt: convert(faAt, 'far'),
  farCalendar: convert(faCalendar, 'far'),
  farCalendarAlt: convert(faCalendarAlt, 'far'),
  farCheck: convert(faCheck, 'far'),
  farFileAlt: convert(faFileAlt, 'far'),
  farFilePdf: convert(faFilePdf, 'far'),
  farGavel: convert(faGavel, 'far'),
  farHands: convert(faHands, 'far'),
  farHome: convert(faHome, 'far'),
  farIdCard: convert(faIdCard, 'far'),
  farLevelUp: convert(faLevelUpAlt, 'far', 'level-up'),
  farList: convert(faList, 'far'),
  farMap: convert(faMap, 'far'),
  farMobile: convert(faMobileAlt, 'far', 'mobile'),
  farMobileAlt: convert(faMobileAlt, 'far'),
  farPencil: convert(faPencilAlt, 'far', 'pencil'),
  farPlus: convert(faPlus, 'far'),
  farSearch: convert(faSearch, 'far'),
  farSpinner: convert(faSpinner, 'far'),
  farTrash: convert(faTrash, 'far'),
  farUser: convert(faUser, 'far'),
  fasArrowDown: convert(faArrowDown, 'fas'),
  fasArrowUp: convert(faArrowUp, 'fas'),
  fasCheckCircle: convert(faCheckCircle, 'fas'),
  fasChevronDown: convert(faChevronDown, 'fas'),
  fasChevronUp: convert(faChevronUp, 'fas'),
  fasCircle: convert(faCircle, 'fas'),
  fasExclamationCircle: convert(faExclamationCircle, 'fas'),
  fasExclamationTriangle: convert(faExclamationTriangle, 'fas'),
  fasHome: convert(faHome, 'fas'),
  fasInfo: convert(faInfo, 'fas'),
  fasInfoCircle: convert(faInfoCircle, 'fas'),
  fasMapMarkerAlt: convert(faMapMarkerAlt, 'fas')
}

export default icons
