// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faCalendar,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faFemale,
  faFile,
  faFileAlt,
  faFilePdf,
  faFileSpreadsheet,
  faGavel,
  faHandHolding,
  faHands,
  faHiking,
  faHomeAlt,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignIn,
  faSignOut,
  faStar,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers
} from '@fortawesome/pro-light-svg-icons'

import {
  faAngleRight as farAngleRight,
  faAt as farAt,
  faCalendar as farCalendar,
  faCalendarAlt as farCalendarAlt,
  faCheck as farCheck,
  faFileAlt as farFileAlt,
  faFilePdf as farFilePdf,
  faGavel as farGavel,
  faHands as farHands,
  faHome as farHome,
  faIdCard as farIdCard,
  faLevelUp as farLevelUp,
  faList as farList,
  faMap as farMap,
  faMobile as farMobile,
  faMobileAlt as farMobileAlt,
  faPencil as farPencil,
  faPlus as farPlus,
  faSearch as farSearch,
  faSpinner as farSpinner,
  faTrash as farTrash,
  faUser as farUser
} from '@fortawesome/pro-regular-svg-icons'

import {
  faArrowDown as fasArrowDown,
  faArrowUp as fasArrowUp,
  faCheckCircle as fasCheckCircle,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faCircle as fasCircle,
  faExclamationCircle as fasExclamationCircle,
  faExclamationTriangle as fasExclamationTriangle,
  faHome as fasHome,
  faInfo as fasInfo,
  faInfoCircle as fasInfoCircle,
  faMapMarkerAlt as fasMapMarkerAlt,
} from '@fortawesome/free-solid-svg-icons'

import { IconSet } from './types'

const icons: IconSet = {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faCalendar,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faFemale,
  faFile,
  faFileAlt,
  faFilePdf,
  faFileSpreadsheet,
  faGavel,
  faHandHolding,
  faHands,
  faHiking,
  faHomeAlt,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignIn,
  faSignOut,
  faStar,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers,
  farAngleRight,
  farAt,
  farCalendar,
  farCalendarAlt,
  farCheck,
  farFileAlt,
  farFilePdf,
  farGavel,
  farHands,
  farHome,
  farIdCard,
  farLevelUp,
  farList,
  farMap,
  farMobile,
  farMobileAlt,
  farPencil,
  farPlus,
  farSearch,
  farSpinner,
  farTrash,
  farUser,
  fasArrowDown,
  fasArrowUp,
  fasCheckCircle,
  fasChevronDown,
  fasChevronUp,
  fasCircle,
  fasExclamationCircle,
  fasExclamationTriangle,
  fasHome,
  fasInfo,
  fasInfoCircle,
  fasMapMarkerAlt
}

export default icons
