// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import { IconDefinition } from '@fortawesome/fontawesome-svg-core'

export interface IconSet {
  faAbacus: IconDefinition
  faAngleDown: IconDefinition
  faAngleLeft: IconDefinition
  faAngleRight: IconDefinition
  faArrowDown: IconDefinition
  faArrowLeft: IconDefinition
  faArrowRight: IconDefinition
  faAngleUp: IconDefinition
  faArrowUp: IconDefinition
  faCalendar: IconDefinition
  faCalendarAlt: IconDefinition
  faCheck: IconDefinition
  faCheckCircle: IconDefinition
  faChevronDown: IconDefinition
  faChevronLeft: IconDefinition
  faChevronRight: IconDefinition
  faChevronUp: IconDefinition
  faChild: IconDefinition
  faClock: IconDefinition
  faCoins: IconDefinition
  faCopy: IconDefinition
  faDatabase: IconDefinition
  faDiagnoses: IconDefinition
  faEnvelope: IconDefinition
  faEuroSign: IconDefinition
  faEllipsisVAlt: IconDefinition
  faEye: IconDefinition
  faEyeSlash: IconDefinition
  faExchange: IconDefinition
  faExclamation: IconDefinition
  faExclamationTriangle: IconDefinition
  faFemale: IconDefinition
  faFile: IconDefinition
  faFileAlt: IconDefinition
  faFilePdf: IconDefinition
  faFileSpreadsheet: IconDefinition
  faGavel: IconDefinition
  faHandHolding: IconDefinition
  faHands: IconDefinition
  faHiking: IconDefinition
  faHomeAlt: IconDefinition
  faHourglassEnd: IconDefinition
  faHourglassStart: IconDefinition
  faInfo: IconDefinition
  faInfoCircle: IconDefinition
  faLink: IconDefinition
  faMapMarkerAlt: IconDefinition
  faMeh: IconDefinition
  faMoneyCheck: IconDefinition
  faMoneyCheckEdit: IconDefinition
  faPen: IconDefinition
  faPercentage: IconDefinition
  faPlay: IconDefinition
  faPlus: IconDefinition
  faPlusCircle: IconDefinition
  faQuestion: IconDefinition
  faQuestionCircle: IconDefinition
  faSearch: IconDefinition
  faSignIn: IconDefinition
  faSignOut: IconDefinition
  faStar: IconDefinition
  faSync: IconDefinition
  faTimes: IconDefinition
  faTrash: IconDefinition
  faUndo: IconDefinition
  faUser: IconDefinition
  faUserAltSlash: IconDefinition
  faUserFriends: IconDefinition
  faUsers: IconDefinition
  farAngleRight: IconDefinition
  farAt: IconDefinition
  farCalendar: IconDefinition
  farCalendarAlt: IconDefinition
  farCheck: IconDefinition
  farFileAlt: IconDefinition
  farFilePdf: IconDefinition
  farGavel: IconDefinition
  farHands: IconDefinition
  farHome: IconDefinition
  farIdCard: IconDefinition
  farLevelUp: IconDefinition
  farList: IconDefinition
  farMap: IconDefinition
  farMobile: IconDefinition
  farMobileAlt: IconDefinition
  farPencil: IconDefinition
  farPlus: IconDefinition
  farSearch: IconDefinition
  farSpinner: IconDefinition
  farTrash: IconDefinition
  farUser: IconDefinition
  fasArrowDown: IconDefinition
  fasArrowUp: IconDefinition
  fasCheckCircle: IconDefinition
  fasChevronDown: IconDefinition
  fasChevronUp: IconDefinition
  fasCircle: IconDefinition
  fasExclamationCircle: IconDefinition
  fasExclamationTriangle: IconDefinition
  fasHome: IconDefinition
  fasInfo: IconDefinition
  fasInfoCircle: IconDefinition
  fasMapMarkerAlt: IconDefinition
}
