# SPDX-FileCopyrightText: 2017-2021 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@0.1.0

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.0.2

jobs:
  generate-config:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Generate pipeline
          command: |
            erb -T- .circleci/template.yml > .circleci/generated.yml
            cat .circleci/generated.yml
      - continuation/continue:
          parameters: '{}'
          configuration_path: .circleci/generated.yml

workflows:
  setup-workflow:
    jobs:
      - generate-config
