# SPDX-FileCopyrightText: 2017-2022 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "Disabled"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
