#!/bin/bash

# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

set -e

# This is helper script to run build always and then execute docker-compose.

cd "$( dirname "${BASH_SOURCE[0]}")"

if [ "$1" = "up" ]; then
    cd theme
    npm install
    npm run build
    cd -
    docker-compose build
fi

docker-compose $@
