// SPDX-FileCopyrightText: 2023-2025 City of Oulu
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package fi.espoo.evaka.oulu.payment.service

import fi.espoo.evaka.oulu.util.FieldType

// NB, I have no idea what many of these things would properly be in English...
enum class PaymentFieldName {
    INTIME_COMPANY_ID,
    PROVIDER_ID,
    INVOICE_ID,
    INVOICE_ACCEPTANCE,
    VOUCHER_TYPE,
    VOUCHER_NUMBER,
    VOUCHER_DATE,
    INVOICE_TYPE,
    ACCOUNT_SUGGESTION,
    PERIOD,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_SUM,
    INVOICE_1,
    CURRENCY,
    CASHBOX_DATE,
    CASHBOX_SUM,
    CASHBOX_MINUS,
    DEBT_ACCOUNT,
    SI_DEBT_ACCOUNT,
    KP_PURCHASE_ACCOUNT,
    SI_PURCHASE_ACCOUNT,
    KP_CASHBOX_ACCOUNT,
    SI_CASHBOX_ACCOUNT,
    KP_OTHER_ACCOUNT,
    SI_OTHER_ACCOUNT,
    SI_KERO_ACCOUNT,
    KP_KERO_ACCOUNT,
    STATS,
    CALC_IDENTIFIER,
    RESP_PERSON,
    FACTORING_NUMBER,
    MACHINE_REFERENCE_NUMBER,
    APPR_TARGET,
    ALPHABETICAL_NAME,
    NAME,
    ADDRESS1,
    ADDRESS2,
    POSTAL_NUMBER,
    POSTAL_ADDR,
    COUNTRY,
    LANGUAGE,
    COUNTRY_CODE,
    BANK,
    BANK_ACCOUNT,
    NOTE,
    VAT_PERIOD,
    VAT_VAL,
    INVOICE_2,
    RECLAMATION_DATE,
    PAYMENT_TERM,
    PAYMENT_MESSAGE,
    INVOICE_BANK_ACCOUNT,
    KOM_TRANSFER_BAN,
    VALUATION_BAN,
    PAYMENT_TERM_CODE,
    EURO_CODE,
    PROVIDER_ADDITIONAL_KEY,
    APP_KEY,
    SUBSTITUTE,
    ADDITIONAL_INFO,
    BANKS_2_3,
    FACT_PROVIDER_ADD_KEY,
    INVOICE_ID_ARCHIVE,
    XML_ATTACHMENT_ID,
    INVOICE_ID_2,
    PICTURE_FILE,
    INT_REF_NRO,
    BANK_BIC_CODE,
    SUBLEDGER,
    DOC_ID,
    SUBST_DOC_ID,
    CONSTRUCTION_KEY,
    CONSTRUCTION_NUMBER,
    CONTRACT,
    CREDIT_TARGET_2,
    SUBSTITUTE_FIELD,
    BREAKDOWN_TYPE,
    DESCRIPTION,
    SUB_ACCOUNT,
    VAT_CODE,
    AMOUNT1,
    AMOUNT2,
    DELIVERY_PERIOD,
    VAT_BALANCE_SUM,
    ACCURUAL_ACCOUNT,
    ACCURUAL_PERIODS,
    ACCURUAL_START,
    FIXED_ASSET_ITEM,
    KOM_TARGET_NAME,
    KOM_TARGET_RESP_PERSON,
    KOM_TARGET_GROUP,
    KOM_TARGET_REM_GROUP,
    KOM_TARGET_START_DATE,
    APPROVER,
    APPROVE_DATE,
    INSPECTOR,
    INSPECTOR_DATE,
    ACCOUNT_REFERENCE,
    EMPTY_FIELD,
    ROW_NUMBER,
}

class PaymentField(
    val field: PaymentFieldName,
    val fieldType: FieldType,
    val start: Int,
    val length: Int,
    val decimals: Int = 0,
)

val headerRowFields =
    listOf(
        PaymentField(PaymentFieldName.INTIME_COMPANY_ID, FieldType.ALPHANUMERIC, 1, 2),
        PaymentField(PaymentFieldName.PROVIDER_ID, FieldType.ALPHANUMERIC, 3, 8),
        PaymentField(PaymentFieldName.INVOICE_ID, FieldType.ALPHANUMERIC, 11, 12),
        PaymentField(PaymentFieldName.INVOICE_ACCEPTANCE, FieldType.NUMERIC, 23, 1),
        PaymentField(PaymentFieldName.VOUCHER_TYPE, FieldType.ALPHANUMERIC, 24, 2),
        PaymentField(PaymentFieldName.VOUCHER_NUMBER, FieldType.NUMERIC, 26, 8),
        PaymentField(PaymentFieldName.VOUCHER_DATE, FieldType.ALPHANUMERIC, 34, 6),
        PaymentField(PaymentFieldName.INVOICE_TYPE, FieldType.NUMERIC, 40, 1),
        PaymentField(PaymentFieldName.ACCOUNT_SUGGESTION, FieldType.ALPHANUMERIC, 41, 1),
        PaymentField(PaymentFieldName.PERIOD, FieldType.ALPHANUMERIC, 42, 4),
        PaymentField(PaymentFieldName.INVOICE_DATE, FieldType.ALPHANUMERIC, 46, 6),
        PaymentField(PaymentFieldName.DUE_DATE, FieldType.ALPHANUMERIC, 52, 6),
        PaymentField(PaymentFieldName.INVOICE_SUM, FieldType.NUMERIC, 58, 12),
        PaymentField(PaymentFieldName.INVOICE_1, FieldType.ALPHANUMERIC, 70, 12),
        PaymentField(PaymentFieldName.CURRENCY, FieldType.ALPHANUMERIC, 82, 3),
        PaymentField(PaymentFieldName.CASHBOX_DATE, FieldType.ALPHANUMERIC, 85, 12),
        PaymentField(PaymentFieldName.CASHBOX_SUM, FieldType.ALPHANUMERIC, 97, 24),
        PaymentField(PaymentFieldName.CASHBOX_MINUS, FieldType.ALPHANUMERIC, 121, 24),
        PaymentField(PaymentFieldName.DEBT_ACCOUNT, FieldType.ALPHANUMERIC, 145, 8),
        PaymentField(PaymentFieldName.SI_DEBT_ACCOUNT, FieldType.ALPHANUMERIC, 153, 8),
        PaymentField(PaymentFieldName.KP_PURCHASE_ACCOUNT, FieldType.NUMERIC, 161, 8),
        PaymentField(PaymentFieldName.SI_PURCHASE_ACCOUNT, FieldType.NUMERIC, 169, 8),
        PaymentField(PaymentFieldName.KP_CASHBOX_ACCOUNT, FieldType.NUMERIC, 177, 8),
        PaymentField(PaymentFieldName.SI_CASHBOX_ACCOUNT, FieldType.NUMERIC, 185, 8),
        PaymentField(PaymentFieldName.KP_OTHER_ACCOUNT, FieldType.NUMERIC, 193, 8),
        PaymentField(PaymentFieldName.SI_OTHER_ACCOUNT, FieldType.NUMERIC, 201, 8),
        PaymentField(PaymentFieldName.SI_KERO_ACCOUNT, FieldType.NUMERIC, 209, 8),
        PaymentField(PaymentFieldName.KP_KERO_ACCOUNT, FieldType.NUMERIC, 217, 8),
        PaymentField(PaymentFieldName.STATS, FieldType.ALPHANUMERIC, 225, 12),
        PaymentField(PaymentFieldName.CALC_IDENTIFIER, FieldType.ALPHANUMERIC, 237, 30),
        PaymentField(PaymentFieldName.RESP_PERSON, FieldType.ALPHANUMERIC, 267, 8),
        PaymentField(PaymentFieldName.FACTORING_NUMBER, FieldType.NUMERIC, 275, 8),
        PaymentField(PaymentFieldName.MACHINE_REFERENCE_NUMBER, FieldType.ALPHANUMERIC, 283, 20),
        PaymentField(PaymentFieldName.APPR_TARGET, FieldType.ALPHANUMERIC, 303, 12),
        PaymentField(PaymentFieldName.ALPHABETICAL_NAME, FieldType.ALPHANUMERIC, 315, 8),
        PaymentField(PaymentFieldName.NAME, FieldType.ALPHANUMERIC, 323, 30),
        PaymentField(PaymentFieldName.ADDRESS1, FieldType.ALPHANUMERIC, 353, 30),
        PaymentField(PaymentFieldName.ADDRESS2, FieldType.ALPHANUMERIC, 383, 30),
        PaymentField(PaymentFieldName.POSTAL_NUMBER, FieldType.ALPHANUMERIC, 413, 10),
        PaymentField(PaymentFieldName.POSTAL_ADDR, FieldType.ALPHANUMERIC, 423, 20),
        PaymentField(PaymentFieldName.COUNTRY, FieldType.ALPHANUMERIC, 443, 30),
        PaymentField(PaymentFieldName.LANGUAGE, FieldType.ALPHANUMERIC, 473, 2),
        PaymentField(PaymentFieldName.COUNTRY_CODE, FieldType.ALPHANUMERIC, 475, 4),
        PaymentField(PaymentFieldName.BANK, FieldType.ALPHANUMERIC, 479, 30),
        PaymentField(PaymentFieldName.BANK_ACCOUNT, FieldType.ALPHANUMERIC, 509, 30),
        PaymentField(PaymentFieldName.NOTE, FieldType.ALPHANUMERIC, 539, 60),
        PaymentField(PaymentFieldName.VAT_PERIOD, FieldType.ALPHANUMERIC, 599, 4),
        PaymentField(PaymentFieldName.VAT_VAL, FieldType.ALPHANUMERIC, 603, 1),
        PaymentField(PaymentFieldName.INVOICE_2, FieldType.ALPHANUMERIC, 604, 15),
        PaymentField(PaymentFieldName.RECLAMATION_DATE, FieldType.ALPHANUMERIC, 619, 6),
        PaymentField(PaymentFieldName.PAYMENT_TERM, FieldType.ALPHANUMERIC, 625, 1),
        PaymentField(PaymentFieldName.PAYMENT_MESSAGE, FieldType.ALPHANUMERIC, 626, 1),
        PaymentField(PaymentFieldName.INVOICE_BANK_ACCOUNT, FieldType.ALPHANUMERIC, 627, 1),
        PaymentField(PaymentFieldName.KOM_TRANSFER_BAN, FieldType.ALPHANUMERIC, 628, 1),
        PaymentField(PaymentFieldName.VALUATION_BAN, FieldType.ALPHANUMERIC, 629, 1),
        PaymentField(PaymentFieldName.PAYMENT_TERM_CODE, FieldType.ALPHANUMERIC, 630, 2),
        PaymentField(PaymentFieldName.EURO_CODE, FieldType.ALPHANUMERIC, 632, 1),
        PaymentField(PaymentFieldName.PROVIDER_ADDITIONAL_KEY, FieldType.ALPHANUMERIC, 633, 20),
        PaymentField(PaymentFieldName.APP_KEY, FieldType.ALPHANUMERIC, 653, 2),
        PaymentField(PaymentFieldName.SUBSTITUTE, FieldType.ALPHANUMERIC, 655, 4),
        PaymentField(PaymentFieldName.ADDITIONAL_INFO, FieldType.ALPHANUMERIC, 659, 30),
        PaymentField(PaymentFieldName.BANKS_2_3, FieldType.ALPHANUMERIC, 689, 60),
        PaymentField(PaymentFieldName.FACT_PROVIDER_ADD_KEY, FieldType.ALPHANUMERIC, 749, 20),
        PaymentField(PaymentFieldName.INVOICE_ID_ARCHIVE, FieldType.ALPHANUMERIC, 769, 10),
        PaymentField(PaymentFieldName.XML_ATTACHMENT_ID, FieldType.ALPHANUMERIC, 779, 10),
        PaymentField(PaymentFieldName.INVOICE_ID_2, FieldType.ALPHANUMERIC, 789, 20),
        PaymentField(PaymentFieldName.PICTURE_FILE, FieldType.ALPHANUMERIC, 809, 30),
        PaymentField(PaymentFieldName.INT_REF_NRO, FieldType.ALPHANUMERIC, 839, 25),
        PaymentField(PaymentFieldName.BANK_BIC_CODE, FieldType.ALPHANUMERIC, 864, 33),
        PaymentField(PaymentFieldName.SUBLEDGER, FieldType.ALPHANUMERIC, 897, 4),
        PaymentField(PaymentFieldName.DOC_ID, FieldType.ALPHANUMERIC, 901, 50),
        PaymentField(PaymentFieldName.SUBST_DOC_ID, FieldType.ALPHANUMERIC, 951, 14),
        PaymentField(PaymentFieldName.CONSTRUCTION_KEY, FieldType.ALPHANUMERIC, 965, 35),
        PaymentField(PaymentFieldName.CONSTRUCTION_NUMBER, FieldType.ALPHANUMERIC, 1000, 50),
        PaymentField(PaymentFieldName.CONTRACT, FieldType.ALPHANUMERIC, 1050, 20),
        PaymentField(PaymentFieldName.CREDIT_TARGET_2, FieldType.ALPHANUMERIC, 1070, 20),
        PaymentField(PaymentFieldName.SUBSTITUTE_FIELD, FieldType.ALPHANUMERIC, 1090, 111),
    )

val paymentRowFields =
    listOf(
        PaymentField(PaymentFieldName.INTIME_COMPANY_ID, FieldType.ALPHANUMERIC, 1, 2),
        PaymentField(PaymentFieldName.PROVIDER_ID, FieldType.ALPHANUMERIC, 3, 8),
        PaymentField(PaymentFieldName.INVOICE_ID, FieldType.ALPHANUMERIC, 11, 12),
        PaymentField(PaymentFieldName.INVOICE_ACCEPTANCE, FieldType.NUMERIC, 23, 1),
        PaymentField(PaymentFieldName.VOUCHER_TYPE, FieldType.ALPHANUMERIC, 24, 2),
        PaymentField(PaymentFieldName.VOUCHER_NUMBER, FieldType.NUMERIC, 26, 8),
        PaymentField(PaymentFieldName.VOUCHER_DATE, FieldType.ALPHANUMERIC, 34, 6),
        PaymentField(PaymentFieldName.INVOICE_TYPE, FieldType.NUMERIC, 40, 1),
        PaymentField(PaymentFieldName.BREAKDOWN_TYPE, FieldType.ALPHANUMERIC, 41, 1),
        PaymentField(PaymentFieldName.CALC_IDENTIFIER, FieldType.ALPHANUMERIC, 42, 30),
        PaymentField(PaymentFieldName.KP_PURCHASE_ACCOUNT, FieldType.NUMERIC, 72, 8),
        PaymentField(PaymentFieldName.SI_PURCHASE_ACCOUNT, FieldType.NUMERIC, 80, 8),
        PaymentField(PaymentFieldName.KP_CASHBOX_ACCOUNT, FieldType.NUMERIC, 88, 8),
        PaymentField(PaymentFieldName.SI_CASHBOX_ACCOUNT, FieldType.NUMERIC, 96, 8),
        PaymentField(PaymentFieldName.SI_KERO_ACCOUNT, FieldType.NUMERIC, 104, 8),
        PaymentField(PaymentFieldName.KP_KERO_ACCOUNT, FieldType.NUMERIC, 112, 8),
        PaymentField(PaymentFieldName.KP_OTHER_ACCOUNT, FieldType.NUMERIC, 120, 8),
        PaymentField(PaymentFieldName.SI_OTHER_ACCOUNT, FieldType.NUMERIC, 128, 8),
        PaymentField(PaymentFieldName.INVOICE_SUM, FieldType.NUMERIC, 136, 12),
        PaymentField(PaymentFieldName.DESCRIPTION, FieldType.ALPHANUMERIC, 148, 30),
        PaymentField(PaymentFieldName.SUB_ACCOUNT, FieldType.ALPHANUMERIC, 178, 6),
        PaymentField(PaymentFieldName.VAT_CODE, FieldType.ALPHANUMERIC, 184, 3),
        PaymentField(PaymentFieldName.AMOUNT1, FieldType.ALPHANUMERIC, 187, 12),
        PaymentField(PaymentFieldName.AMOUNT2, FieldType.ALPHANUMERIC, 199, 12),
        PaymentField(PaymentFieldName.DELIVERY_PERIOD, FieldType.ALPHANUMERIC, 211, 4),
        PaymentField(PaymentFieldName.VAT_BALANCE_SUM, FieldType.ALPHANUMERIC, 215, 12),
        PaymentField(PaymentFieldName.ADDITIONAL_INFO, FieldType.ALPHANUMERIC, 227, 30),
        PaymentField(PaymentFieldName.ACCURUAL_ACCOUNT, FieldType.ALPHANUMERIC, 257, 16),
        PaymentField(PaymentFieldName.ACCURUAL_PERIODS, FieldType.ALPHANUMERIC, 273, 2),
        PaymentField(PaymentFieldName.ACCURUAL_START, FieldType.ALPHANUMERIC, 275, 4),
        PaymentField(PaymentFieldName.FIXED_ASSET_ITEM, FieldType.ALPHANUMERIC, 279, 16),
        PaymentField(PaymentFieldName.KOM_TARGET_NAME, FieldType.ALPHANUMERIC, 295, 60),
        PaymentField(PaymentFieldName.KOM_TARGET_RESP_PERSON, FieldType.ALPHANUMERIC, 355, 30),
        PaymentField(PaymentFieldName.KOM_TARGET_GROUP, FieldType.ALPHANUMERIC, 385, 8),
        PaymentField(PaymentFieldName.KOM_TARGET_REM_GROUP, FieldType.ALPHANUMERIC, 393, 8),
        PaymentField(PaymentFieldName.KOM_TARGET_START_DATE, FieldType.ALPHANUMERIC, 401, 6),
        PaymentField(PaymentFieldName.KOM_TRANSFER_BAN, FieldType.ALPHANUMERIC, 407, 1),
        PaymentField(PaymentFieldName.APPROVER, FieldType.ALPHANUMERIC, 408, 32),
        PaymentField(PaymentFieldName.APPROVE_DATE, FieldType.ALPHANUMERIC, 440, 6),
        PaymentField(PaymentFieldName.INSPECTOR, FieldType.ALPHANUMERIC, 446, 30),
        PaymentField(PaymentFieldName.INSPECTOR_DATE, FieldType.ALPHANUMERIC, 476, 6),
        PaymentField(PaymentFieldName.ACCOUNT_REFERENCE, FieldType.ALPHANUMERIC, 482, 10),
        PaymentField(PaymentFieldName.CONSTRUCTION_KEY, FieldType.ALPHANUMERIC, 527, 35),
        PaymentField(PaymentFieldName.CONSTRUCTION_NUMBER, FieldType.ALPHANUMERIC, 562, 50),
        PaymentField(PaymentFieldName.EMPTY_FIELD, FieldType.ALPHANUMERIC, 612, 7),
        PaymentField(PaymentFieldName.CONTRACT, FieldType.ALPHANUMERIC, 619, 20),
        PaymentField(PaymentFieldName.ROW_NUMBER, FieldType.ALPHANUMERIC, 639, 4),
        PaymentField(PaymentFieldName.EMPTY_FIELD, FieldType.ALPHANUMERIC, 643, 16),
        PaymentField(PaymentFieldName.EMPTY_FIELD, FieldType.ALPHANUMERIC, 659, 30),
        PaymentField(PaymentFieldName.EMPTY_FIELD, FieldType.ALPHANUMERIC, 689, 212),
        PaymentField(PaymentFieldName.EMPTY_FIELD, FieldType.ALPHANUMERIC, 901, 300),
    )
