// SPDX-FileCopyrightText: 2017-2021 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

export type UnitAction =
  | 'ACCEPT_PLACEMENT_PROPOSAL'
  | 'CREATE_PLACEMENT'
  | 'DELETE_ACL_SPECIAL_EDUCATION_TEACHER'
  | 'DELETE_ACL_STAFF'
  | 'DELETE_ACL_UNIT_SUPERVISOR'
  | 'INSERT_ACL_SPECIAL_EDUCATION_TEACHER'
  | 'INSERT_ACL_STAFF'
  | 'INSERT_ACL_UNIT_SUPERVISOR'
  | 'READ_ACL'
  | 'READ_APPLICATION_WITH_ASSISTANCE_NEED'
  | 'READ_APPLICATION_WITHOUT_ASSISTANCE_NEED'
  | 'READ_BACKUP_CARE'
  | 'READ_BASIC'
  | 'READ_DETAILED'
  | 'READ_PLACEMENT'
  | 'READ_PLACEMENT_PLAN'
  | 'UPDATE'
  | 'UPDATE_STAFF_GROUP_ACL'
