#!/bin/sh -e

# SPDX-FileCopyrightText: 2017-2021 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

if [ "${BUILD:-true}" = "true" ] && [ "$1" = "up" ]; then
    ./build.sh
fi

docker-compose -f docker-compose.yml -f docker-compose.e2e.yml $@
