#!/bin/bash

# SPDX-FileCopyrightText: 2017-2022 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

if [ "${BUILD:-true}" = "true" ] && ( [ "$1" = "up" ] || [ "$1" = "run" ] ); then
    docker-compose -f docker-compose.yml -f docker-compose.integration.yml build --parallel
fi

docker-compose -f docker-compose.yml -f docker-compose.integration.yml $@
