#!/bin/bash

# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

set -e

cd "$( dirname "${BASH_SOURCE[0]}")"

docker-compose -f docker-compose.yml -f docker-compose.keycloak.yml $@

