#!/bin/sh -e

# SPDX-FileCopyrightText: 2017-2021 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

export UID="${UID:-$(id -u)}"
export GID="${GID:-$(id -g)}"
export GITHUB_REPOSITORY_OWNER="${GITHUB_REPOSITORY_OWNER:-$(git remote get-url origin | sed 's/:/\//g' | rev | cut -d'/' -f2 |rev)}"

if [ "${BUILD:-true}" = "true" ] && ( [ "$1" = "up" ] || [ "$1" = "run" ] ); then
    docker compose -f docker-compose.yml -f docker-compose.e2e.yml build --parallel # not building playwright
fi

docker compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.e2e-tests.yml $@
