#!/bin/sh -e

# SPDX-FileCopyrightText: 2017-2021 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

if test -z "$UID"; then
  export UID="$(id -u)"
fi
if test -z "$GID"; then
  export GID="$(id -g)"
fi

if [ "${BUILD:-true}" = "true" ] && ( [ "$1" = "up" ] || [ "$1" = "run" ] ); then
    docker compose -f docker-compose.yml -f docker-compose.e2e.yml build --parallel # not building playwright
fi

docker compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.e2e-tests.yml $@
