// SPDX-FileCopyrightText: 2017-2022 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

declare module '@fortawesome/pro-light-svg-icons/*'
declare module '@fortawesome/pro-regular-svg-icons/*'
declare module '@fortawesome/pro-solid-svg-icons/*'

type IconDefinition = import('@fortawesome/fontawesome-svg-core').IconDefinition

declare module 'Icons' {
  const faAbacus: IconDefinition
  const faAngleDown: IconDefinition
  const faAngleLeft: IconDefinition
  const faAngleRight: IconDefinition
  const faArrowDown: IconDefinition
  const faArrowDownToLine: IconDefinition
  const faArrowLeft: IconDefinition
  const faArrowRight: IconDefinition
  const faArrowRotateLeft: IconDefinition
  const faAngleUp: IconDefinition
  const faArrowUp: IconDefinition
  const faBars: IconDefinition
  const faBabyCarriage: IconDefinition
  const faBoxArchive: IconDefinition
  const faCalendar: IconDefinition
  const faCalendarAlt: IconDefinition
  const faCalendarPlus: IconDefinition
  const faCar: IconDefinition
  const faCheck: IconDefinition
  const faCheckCircle: IconDefinition
  const faChevronDown: IconDefinition
  const faChevronLeft: IconDefinition
  const faChevronRight: IconDefinition
  const faChevronUp: IconDefinition
  const faChild: IconDefinition
  const faCircleEllipsis: IconDefinition
  const faCircleExclamation: IconDefinition
  const faClock: IconDefinition
  const faCoins: IconDefinition
  const faComment: IconDefinition
  const fasComment: IconDefinition
  const faCopy: IconDefinition
  const faCommentAlt: IconDefinition
  const faComments: IconDefinition
  const faDatabase: IconDefinition
  const faDash: IconDefinition
  const faDiagnoses: IconDefinition
  const faEnvelope: IconDefinition
  const faEuroSign: IconDefinition
  const faEllipsisVAlt: IconDefinition
  const faEye: IconDefinition
  const faEyeSlash: IconDefinition
  const faExchange: IconDefinition
  const faExclamation: IconDefinition
  const faExclamationTriangle: IconDefinition
  const faExternalLink: IconDefinition
  const faFemale: IconDefinition
  const faFile: IconDefinition
  const fasFile: IconDefinition
  const faFileAlt: IconDefinition
  const fasFileAlt: IconDefinition
  const faFileImage: IconDefinition
  const faFilePdf: IconDefinition
  const faFileSpreadsheet: IconDefinition
  const faFileWord: IconDefinition
  const faGavel: IconDefinition
  const faHandHolding: IconDefinition
  const faHiking: IconDefinition
  const faHome: IconDefinition
  const faHourglassEnd: IconDefinition
  const faHourglassStart: IconDefinition
  const faInfo: IconDefinition
  const faInfoCircle: IconDefinition
  const faLink: IconDefinition
  const faList: IconDefinition
  const faLockAlt: IconDefinition
  const faLockOpenAlt: IconDefinition
  const faMapMarkerAlt: IconDefinition
  const faMeh: IconDefinition
  const faMoneyBillWave: IconDefinition
  const faMoneyCheck: IconDefinition
  const faMoneyCheckEdit: IconDefinition
  const faPaperclip: IconDefinition
  const faPen: IconDefinition
  const faPercentage: IconDefinition
  const faPlay: IconDefinition
  const faPlus: IconDefinition
  const faPlusCircle: IconDefinition
  const faRedo: IconDefinition
  const faQuestion: IconDefinition
  const faQuestionCircle: IconDefinition
  const faSearch: IconDefinition
  const faSignIn: IconDefinition
  const faSignOut: IconDefinition
  const faStickyNote: IconDefinition
  const faSync: IconDefinition
  const faThermometer: IconDefinition
  const faTimes: IconDefinition
  const faTrash: IconDefinition
  const faTreePalm: IconDefinition
  const faUndo: IconDefinition
  const faUser: IconDefinition
  const fasUser: IconDefinition
  const fasUserMinus: IconDefinition
  const faUserAltSlash: IconDefinition
  const faUserFriends: IconDefinition
  const faUserMinus: IconDefinition
  const faUserUnlock: IconDefinition
  const faUsers: IconDefinition
  const farBars: IconDefinition
  const farFileAlt: IconDefinition
  const farGavel: IconDefinition
  const farMap: IconDefinition
  const farSignOut: IconDefinition
  const farStickyNote: IconDefinition
  const farXmark: IconDefinition
  const fasCalendar: IconDefinition
  const fasCaretUp: IconDefinition
  const fasCaretDown: IconDefinition
  const fasCaretLeft: IconDefinition
  const fasCaretRight: IconDefinition
  const fasCheckCircle: IconDefinition
  const fasChevronDown: IconDefinition
  const fasChevronUp: IconDefinition
  const fasChild: IconDefinition
  const fasCommentAltLines: IconDefinition
  const fasEnvelope: IconDefinition
  const fasExclamationTriangle: IconDefinition
  const fasInfo: IconDefinition
  const fasMapMarkerAlt: IconDefinition
  const fasArrowDown: IconDefinition
  const fasArrowUp: IconDefinition
  const farUser: IconDefinition
  const farUsers: IconDefinition
  const faTruck: IconDefinition
  const faPhone: IconDefinition
  const faCalendarTimes: IconDefinition
  const faUpRightAndDownLeftFromCenter: IconDefinition
  const faDownLeftAndUpRightToCenter: IconDefinition
  const faMagnifyingGlassPlus: IconDefinition
  const faMagnifyingGlassMinus: IconDefinition
  const faListTimeline: IconDefinition
  const faReply: IconDefinition
}
