// SPDX-FileCopyrightText: 2017-2022 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faCommentAlt as farCommentAlt,
  faFileAlt as farFileAlt,
  faMap as farMap,
  faStickyNote as farStickyNote,
  faUser as farUser
} from '@fortawesome/free-regular-svg-icons'
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faBabyCarriage,
  faCalendarAlt,
  faCalendarPlus,
  faCaretUp,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faCircleExclamation,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faExchangeAlt,
  faExclamation,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFemale,
  faFile,
  faFileAlt,
  faFileCsv,
  faFileImage,
  faFilePdf,
  faFileWord,
  faGavel,
  faHandHolding,
  faHiking,
  faHome,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faLock,
  faMapMarkerAlt,
  faMeh,
  faMoneyBillWave,
  faMoneyCheck,
  faPaperclip,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faStickyNote,
  faSun,
  faSync,
  faThermometer,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUserLock,
  faUserMinus,
  faUsers,
  faComments,
  faCommentAlt,
  faTruck,
  faPhone,
  faCalendarTimes,
  faRedo,
  faUpRightAndDownLeftFromCenter,
  faDownLeftAndUpRightToCenter
} from '@fortawesome/free-solid-svg-icons'
import { faLockOpen } from '@fortawesome/free-solid-svg-icons/faLockOpen'

import { IconSet } from '.'

const icons: IconSet = {
  faAbacus: faPercentage,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowDownToLine: faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faBabyCarriage,
  faCalendarAlt,
  faCalendarPlus,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  fasChild: faChild,
  faCircleExclamation,
  faClock,
  faCoins,
  faCommentAlt: farCommentAlt,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  fasEnvelope: faEnvelope,
  faEuroSign,
  faEllipsisVAlt: faEllipsisV,
  faEye,
  faEyeSlash,
  faExchange: faExchangeAlt,
  faExclamation,
  faExclamationTriangle,
  faExternalLink: faExternalLinkAlt,
  faFemale,
  faFile,
  faFileAlt,
  faFileImage,
  faFilePdf,
  faFileSpreadsheet: faFileCsv,
  faFileWord,
  faGavel,
  faHandHolding,
  faHiking,
  faHome,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faLockAlt: faLock,
  faLockOpenAlt: faLockOpen,
  faMapMarkerAlt,
  faMeh,
  faMoneyBillWave,
  faMoneyCheck,
  faMoneyCheckEdit: faMoneyCheck,
  faPaperclip,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faRedo,
  faSearch,
  faSignIn: faSignInAlt,
  faSignOut: faSignOutAlt,
  faStickyNote,
  farStickyNote,
  faSync,
  faThermometer,
  faTimes,
  faTrash,
  faTreePalm: faSun,
  faUndo,
  faUser,
  fasUser: faUser,
  faUserAltSlash,
  faUserFriends,
  faUserMinus,
  faUserUnlock: faUserLock,
  faUsers,
  farFileAlt,
  farGavel: faGavel,
  farMap,
  fasCaretUp: faCaretUp,
  fasCaretDown: faCaretDown,
  fasCaretLeft: faCaretLeft,
  fasCaretRight: faCaretRight,
  fasCheckCircle: faCheckCircle,
  fasChevronDown: faChevronDown,
  fasChevronUp: faChevronUp,
  fasCommentAltLines: faCommentAlt,
  fasExclamationTriangle: faExclamationTriangle,
  fasInfo: faInfo,
  fasMapMarkerAlt: faMapMarkerAlt,
  fasArrowDown: faArrowDown,
  fasArrowUp: faArrowUp,
  farUser,
  farUsers: faUsers,
  faComments,
  faTruck,
  faPhone,
  faCalendarTimes,
  faUpRightAndDownLeftFromCenter,
  faDownLeftAndUpRightToCenter
}

export default icons
