// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faExternalLink,
  faFemale,
  faFile,
  faFileAlt,
  faFileImage,
  faFilePdf,
  faFileWord,
  faFileSpreadsheet,
  faGavel,
  faHandHolding,
  faHiking,
  faHomeAlt,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignIn,
  faSignOut,
  faStickyNote,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers,
  faComments
} from '@fortawesome/pro-light-svg-icons'

import {
  faFileAlt as farFileAlt,
  faGavel as farGavel,
  faMap as farMap,
  faStickyNote as farStickyNote
} from '@fortawesome/pro-regular-svg-icons'

import {
  faCaretUp as fasCaretUp,
  faCaretDown as fasCaretDown,
  faCheckCircle as fasCheckCircle,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faExclamationTriangle as fasExclamationTriangle,
  faInfo as fasInfo,
  faMapMarkerAlt as fasMapMarkerAlt,
  faArrowDown as fasArrowDown,
  faArrowUp as fasArrowUp
} from '@fortawesome/free-solid-svg-icons'

import { IconSet } from '.'

/* eslint-disable @typescript-eslint/no-unsafe-assignment */
const icons: IconSet = {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faExternalLink,
  faFemale,
  faFile,
  faFileAlt,
  faFileImage,
  faFilePdf,
  faFileSpreadsheet,
  faFileWord,
  faGavel,
  faHandHolding,
  faHiking,
  faHomeAlt,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignIn,
  faSignOut,
  faStickyNote,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers,
  farFileAlt,
  farGavel,
  farMap,
  fasCaretUp,
  fasCaretDown,
  fasCheckCircle,
  fasChevronDown,
  fasChevronUp,
  fasExclamationTriangle,
  fasInfo,
  fasMapMarkerAlt,
  fasArrowDown,
  fasArrowUp,
  farStickyNote,
  farUser: faUser,
  faComments
}

export default icons
