// SPDX-FileCopyrightText: 2017-2022 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faArrowDown as fasArrowDown,
  faArrowUp as fasArrowUp,
  faCaretDown as fasCaretDown,
  faCaretLeft as fasCaretLeft,
  faCaretRight as fasCaretRight,
  faCaretUp as fasCaretUp,
  faCheckCircle as fasCheckCircle,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faChild as fasChild,
  faEnvelope as fasEnvelope,
  faExclamationTriangle as fasExclamationTriangle,
  faInfo as fasInfo,
  faMapMarkerAlt as fasMapMarkerAlt,
  faUser as fasUser
} from '@fortawesome/free-solid-svg-icons'
import {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faBabyCarriage,
  faCalendarAlt,
  faCalendarPlus,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faCircleExclamation,
  faClock,
  faCoins,
  faCommentAlt,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faExternalLink,
  faFemale,
  faFile,
  faFileAlt,
  faFileImage,
  faFilePdf,
  faFileWord,
  faFileSpreadsheet,
  faGavel,
  faHandHolding,
  faHiking,
  faHome,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faLockAlt,
  faLockOpenAlt,
  faMapMarkerAlt,
  faMeh,
  faMoneyBillWave,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPaperclip,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faRedo,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignIn,
  faSignOut,
  faStickyNote,
  faSync,
  faThermometer,
  faTimes,
  faTrash,
  faTreePalm,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUserMinus,
  faUserUnlock,
  faUsers,
  faComments,
  faTruck,
  faPhone,
  faCalendarTimes,
  faUpRightAndDownLeftFromCenter,
  faDownLeftAndUpRightToCenter
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
} from '@fortawesome/pro-light-svg-icons'
import {
  faFileAlt as farFileAlt,
  faGavel as farGavel,
  faMap as farMap,
  faStickyNote as farStickyNote,
  faUsers as farUsers
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
} from '@fortawesome/pro-regular-svg-icons'
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { faCommentAltLines as fasCommentAltLines } from '@fortawesome/pro-solid-svg-icons'

import { IconSet } from '.'

/* eslint-disable @typescript-eslint/no-unsafe-assignment */
const icons: IconSet = {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faBars,
  faBabyCarriage,
  faCalendarAlt,
  faCalendarPlus,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  fasChild,
  faCircleExclamation,
  faClock,
  faCoins,
  faCommentAlt,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  fasEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faExternalLink,
  faFemale,
  faFile,
  faFileAlt,
  faFileImage,
  faFilePdf,
  faFileSpreadsheet,
  faFileWord,
  faGavel,
  faHandHolding,
  faHiking,
  faHome,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faList,
  faLockAlt,
  faLockOpenAlt,
  faMapMarkerAlt,
  faMeh,
  faMoneyBillWave,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPaperclip,
  faPen,
  faPercentage,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faRedo,
  faSearch,
  faSignIn,
  faSignOut,
  faStickyNote,
  faSync,
  faThermometer,
  faTimes,
  faTrash,
  faTreePalm,
  faUndo,
  faUser,
  fasUser,
  faUserAltSlash,
  faUserFriends,
  faUserMinus,
  faUserUnlock,
  faUsers,
  farFileAlt,
  farGavel,
  farMap,
  fasCaretUp,
  fasCaretDown,
  fasCaretLeft,
  fasCaretRight,
  fasCheckCircle,
  fasChevronDown,
  fasChevronUp,
  fasCommentAltLines,
  fasExclamationTriangle,
  fasInfo,
  fasMapMarkerAlt,
  fasArrowDown,
  fasArrowUp,
  farStickyNote,
  farUser: faUser,
  farUsers,
  faComments,
  faTruck,
  faPhone,
  faCalendarTimes,
  faUpRightAndDownLeftFromCenter,
  faDownLeftAndUpRightToCenter
}

export default icons
