// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package fi.espoo.evaka.msg.sficlient.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
  * 2019-03-11T16:08:39.152+02:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "ViranomaispalvelutService",
                  wsdlLocation = "file:/home/olli/development/evaka-message-service/src/main/resources/wsdl/Viranomaispalvelut.wsdl",
                  targetNamespace = "http://www.suomi.fi/asiointitili")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00", comments = "Apache CXF 3.3.1")
public class ViranomaispalvelutService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public final static QName SERVICE = new QName("http://www.suomi.fi/asiointitili", "ViranomaispalvelutService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public final static QName ViranomaispalvelutPort = new QName("http://www.suomi.fi/asiointitili", "ViranomaispalvelutPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/olli/development/evaka-message-service/src/main/resources/wsdl/Viranomaispalvelut.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ViranomaispalvelutService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/olli/development/evaka-message-service/src/main/resources/wsdl/Viranomaispalvelut.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public ViranomaispalvelutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public ViranomaispalvelutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public ViranomaispalvelutService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public ViranomaispalvelutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public ViranomaispalvelutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public ViranomaispalvelutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Viranomaispalvelut
     */
    @WebEndpoint(name = "ViranomaispalvelutPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public Viranomaispalvelut getViranomaispalvelutPort() {
        return super.getPort(ViranomaispalvelutPort, Viranomaispalvelut.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Viranomaispalvelut
     */
    @WebEndpoint(name = "ViranomaispalvelutPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.152+02:00")
    public Viranomaispalvelut getViranomaispalvelutPort(WebServiceFeature... features) {
        return super.getPort(ViranomaispalvelutPort, Viranomaispalvelut.class, features);
    }

}
