// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package fi.espoo.evaka.msg.sficlient.soap;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-11T16:08:39.014+02:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://www.suomi.fi/asiointitili", name = "Viranomaispalvelut")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.014+02:00", comments = "Apache CXF 3.3.1")
public interface Viranomaispalvelut {

    @WebMethod(operationName = "HaeAsiakkaita", action = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/HaeAsiakkaita")
    @Action(input = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/HaeAsiakkaita", output = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/HaeAsiakkaitaResponse")
    @RequestWrapper(localName = "HaeAsiakkaita", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.HaeAsiakkaita")
    @ResponseWrapper(localName = "HaeAsiakkaitaResponse", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.HaeAsiakkaitaResponse")
    @WebResult(name = "HaeAsiakkaitaResult", targetNamespace = "http://www.suomi.fi/asiointitili")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.014+02:00")
    public fi.espoo.evaka.msg.sficlient.soap.VastausWS1 haeAsiakkaita(
        @WebParam(name = "Viranomainen", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.Viranomainen viranomainen,
        @WebParam(name = "Kysely", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.KyselyWS1 kysely
    );

    @WebMethod(operationName = "HaeTilaTieto", action = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/HaeTilaTieto")
    @Action(input = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/HaeTilaTieto", output = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/HaeTilaTietoResponse")
    @RequestWrapper(localName = "HaeTilaTieto", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.HaeTilaTieto")
    @ResponseWrapper(localName = "HaeTilaTietoResponse", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.HaeTilaTietoResponse")
    @WebResult(name = "HaeTilaTietoResult", targetNamespace = "http://www.suomi.fi/asiointitili")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.014+02:00")
    public fi.espoo.evaka.msg.sficlient.soap.VastausWS10 haeTilaTieto(
        @WebParam(name = "Viranomainen", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.Viranomainen viranomainen,
        @WebParam(name = "Kysely", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.KyselyWS10 kysely
    );

    @WebMethod(operationName = "LahetaViesti", action = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/LahetaViesti")
    @Action(input = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/LahetaViesti", output = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/LahetaViestiResponse")
    @RequestWrapper(localName = "LahetaViesti", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.LahetaViesti")
    @ResponseWrapper(localName = "LahetaViestiResponse", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.LahetaViestiResponse")
    @WebResult(name = "LahetaViestiResult", targetNamespace = "http://www.suomi.fi/asiointitili")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.014+02:00")
    public fi.espoo.evaka.msg.sficlient.soap.VastausWS2A lahetaViesti(
        @WebParam(name = "Viranomainen", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.Viranomainen viranomainen,
        @WebParam(name = "Kysely", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.KyselyWS2A kysely
    );

    @WebMethod(operationName = "LisaaKohteita", action = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/LisaaKohteita")
    @Action(input = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/LisaaKohteita", output = "http://www.suomi.fi/asiointitili/Viranomaispalvelut/LisaaKohteitaResponse")
    @RequestWrapper(localName = "LisaaKohteita", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.LisaaKohteita")
    @ResponseWrapper(localName = "LisaaKohteitaResponse", targetNamespace = "http://www.suomi.fi/asiointitili", className = "fi.espoo.evaka.msg.sficlient.soap.LisaaKohteitaResponse")
    @WebResult(name = "LisaaKohteitaResult", targetNamespace = "http://www.suomi.fi/asiointitili")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-11T16:08:39.014+02:00")
    public fi.espoo.evaka.msg.sficlient.soap.VastausWS2 lisaaKohteita(
        @WebParam(name = "Viranomainen", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.Viranomainen viranomainen,
        @WebParam(name = "Kysely", targetNamespace = "http://www.suomi.fi/asiointitili")
        fi.espoo.evaka.msg.sficlient.soap.KyselyWS2 kysely
    );
}
