// SPDX-FileCopyrightText: 2023-2025 City of Turku
//
// SPDX-License-Identifier: LGPL-2.1-or-later

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 08:17:36 AM UTC 
//


package evaka.instance.turku.invoice.service;



import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ORDERS05 }
     * 
     */
    public ORDERS05 createORDERS05() {
        return new ORDERS05();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC }
     * 
     */
    public ORDERS05 .IDOC createORDERS05IDOC() {
        return new ORDERS05 .IDOC();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDL37 }
     * 
     */
    public ORDERS05 .IDOC.E1EDL37 createORDERS05IDOCE1EDL37() {
        return new ORDERS05 .IDOC.E1EDL37();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1CUCFG }
     * 
     */
    public ORDERS05 .IDOC.E1CUCFG createORDERS05IDOCE1CUCFG() {
        return new ORDERS05 .IDOC.E1CUCFG();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 createORDERS05IDOCE1EDP01() {
        return new ORDERS05 .IDOC.E1EDP01();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 createORDERS05IDOCE1EDP01E1EDC01() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCT1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCT1 createORDERS05IDOCE1EDP01E1EDC01E1EDCT1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCT1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPT1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPT1 createORDERS05IDOCE1EDP01E1EDPT1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPT1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPAD }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPAD createORDERS05IDOCE1EDP01E1EDPAD() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPAD();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPAD.E1TXTH1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPAD.E1TXTH1 createORDERS05IDOCE1EDP01E1EDPADE1TXTH1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPAD.E1TXTH1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPA1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPA1 createORDERS05IDOCE1EDP01E1EDPA1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPA1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP05 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP05 createORDERS05IDOCE1EDP01E1EDP05() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP05();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDKT1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDKT1 createORDERS05IDOCE1EDKT1() {
        return new ORDERS05 .IDOC.E1EDKT1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDKA1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDKA1 createORDERS05IDOCE1EDKA1() {
        return new ORDERS05 .IDOC.E1EDKA1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.EDIDC40 }
     * 
     */
    public ORDERS05 .IDOC.EDIDC40 createORDERS05IDOCEDIDC40() {
        return new ORDERS05 .IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK01 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK01 createORDERS05IDOCE1EDK01() {
        return new ORDERS05 .IDOC.E1EDK01();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK14 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK14 createORDERS05IDOCE1EDK14() {
        return new ORDERS05 .IDOC.E1EDK14();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK03 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK03 createORDERS05IDOCE1EDK03() {
        return new ORDERS05 .IDOC.E1EDK03();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK04 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK04 createORDERS05IDOCE1EDK04() {
        return new ORDERS05 .IDOC.E1EDK04();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK05 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK05 createORDERS05IDOCE1EDK05() {
        return new ORDERS05 .IDOC.E1EDK05();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK02 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK02 createORDERS05IDOCE1EDK02() {
        return new ORDERS05 .IDOC.E1EDK02();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK17 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK17 createORDERS05IDOCE1EDK17() {
        return new ORDERS05 .IDOC.E1EDK17();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK18 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK18 createORDERS05IDOCE1EDK18() {
        return new ORDERS05 .IDOC.E1EDK18();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK35 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK35 createORDERS05IDOCE1EDK35() {
        return new ORDERS05 .IDOC.E1EDK35();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDK36 }
     * 
     */
    public ORDERS05 .IDOC.E1EDK36 createORDERS05IDOCE1EDK36() {
        return new ORDERS05 .IDOC.E1EDK36();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDS01 }
     * 
     */
    public ORDERS05 .IDOC.E1EDS01 createORDERS05IDOCE1EDS01() {
        return new ORDERS05 .IDOC.E1EDS01();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1IDOCENHANCEMENT }
     * 
     */
    public ORDERS05 .IDOC.E1IDOCENHANCEMENT createORDERS05IDOCE1IDOCENHANCEMENT() {
        return new ORDERS05 .IDOC.E1IDOCENHANCEMENT();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDL37 .E1EDL39 }
     * 
     */
    public ORDERS05 .IDOC.E1EDL37 .E1EDL39 createORDERS05IDOCE1EDL37E1EDL39() {
        return new ORDERS05 .IDOC.E1EDL37 .E1EDL39();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDL37 .E1EDL38 }
     * 
     */
    public ORDERS05 .IDOC.E1EDL37 .E1EDL38 createORDERS05IDOCE1EDL37E1EDL38() {
        return new ORDERS05 .IDOC.E1EDL37 .E1EDL38();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDL37 .E1EDL44 }
     * 
     */
    public ORDERS05 .IDOC.E1EDL37 .E1EDL44 createORDERS05IDOCE1EDL37E1EDL44() {
        return new ORDERS05 .IDOC.E1EDL37 .E1EDL44();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1CUCFG.E1CUINS }
     * 
     */
    public ORDERS05 .IDOC.E1CUCFG.E1CUINS createORDERS05IDOCE1CUCFGE1CUINS() {
        return new ORDERS05 .IDOC.E1CUCFG.E1CUINS();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1CUCFG.E1CUPRT }
     * 
     */
    public ORDERS05 .IDOC.E1CUCFG.E1CUPRT createORDERS05IDOCE1CUCFGE1CUPRT() {
        return new ORDERS05 .IDOC.E1CUCFG.E1CUPRT();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1CUCFG.E1CUVAL }
     * 
     */
    public ORDERS05 .IDOC.E1CUCFG.E1CUVAL createORDERS05IDOCE1CUCFGE1CUVAL() {
        return new ORDERS05 .IDOC.E1CUCFG.E1CUVAL();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1CUCFG.E1CUBLB }
     * 
     */
    public ORDERS05 .IDOC.E1CUCFG.E1CUBLB createORDERS05IDOCE1CUCFGE1CUBLB() {
        return new ORDERS05 .IDOC.E1CUCFG.E1CUBLB();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP02 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP02 createORDERS05IDOCE1EDP01E1EDP02() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP02();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1CUREF }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1CUREF createORDERS05IDOCE1EDP01E1CUREF() {
        return new ORDERS05 .IDOC.E1EDP01 .E1CUREF();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1ADDI1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1ADDI1 createORDERS05IDOCE1EDP01E1ADDI1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1ADDI1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP03 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP03 createORDERS05IDOCE1EDP01E1EDP03() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP03();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP04 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP04 createORDERS05IDOCE1EDP01E1EDP04() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP04();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP20 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP20 createORDERS05IDOCE1EDP01E1EDP20() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP20();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP19 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP19 createORDERS05IDOCE1EDP01E1EDP19() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP19();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP17 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP17 createORDERS05IDOCE1EDP01E1EDP17() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP17();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP18 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP18 createORDERS05IDOCE1EDP01E1EDP18() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP18();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP35 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP35 createORDERS05IDOCE1EDP01E1EDP35() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP35();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC02 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC02 createORDERS05IDOCE1EDP01E1EDC01E1EDC02() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC02();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC03 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC03 createORDERS05IDOCE1EDP01E1EDC01E1EDC03() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC03();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC04 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC04 createORDERS05IDOCE1EDP01E1EDC01E1EDC04() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC04();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC05 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC05 createORDERS05IDOCE1EDP01E1EDC01E1EDC05() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC05();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC06 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC06 createORDERS05IDOCE1EDP01E1EDC01E1EDC06() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC06();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC07 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC07 createORDERS05IDOCE1EDP01E1EDC01E1EDC07() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC07();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCA1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCA1 createORDERS05IDOCE1EDP01E1EDC01E1EDCA1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCA1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC19 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC19 createORDERS05IDOCE1EDP01E1EDC01E1EDC19() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC19();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC17 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC17 createORDERS05IDOCE1EDP01E1EDC01E1EDC17() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC17();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC18 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC18 createORDERS05IDOCE1EDP01E1EDC01E1EDC18() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDC18();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCT1 .E1EDCT2 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCT1 .E1EDCT2 createORDERS05IDOCE1EDP01E1EDC01E1EDCT1E1EDCT2() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDC01 .E1EDCT1 .E1EDCT2();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPT1 .E1EDPT2 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPT1 .E1EDPT2 createORDERS05IDOCE1EDP01E1EDPT1E1EDPT2() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPT1 .E1EDPT2();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPAD.E1TXTH1 .E1TXTP1 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPAD.E1TXTH1 .E1TXTP1 createORDERS05IDOCE1EDP01E1EDPADE1TXTH1E1TXTP1() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPAD.E1TXTH1 .E1TXTP1();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDPA1 .E1EDPA3 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDPA1 .E1EDPA3 createORDERS05IDOCE1EDP01E1EDPA1E1EDPA3() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDPA1 .E1EDPA3();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDP01 .E1EDP05 .E1EDPS5 }
     * 
     */
    public ORDERS05 .IDOC.E1EDP01 .E1EDP05 .E1EDPS5 createORDERS05IDOCE1EDP01E1EDP05E1EDPS5() {
        return new ORDERS05 .IDOC.E1EDP01 .E1EDP05 .E1EDPS5();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDKT1 .E1EDKT2 }
     * 
     */
    public ORDERS05 .IDOC.E1EDKT1 .E1EDKT2 createORDERS05IDOCE1EDKT1E1EDKT2() {
        return new ORDERS05 .IDOC.E1EDKT1 .E1EDKT2();
    }

    /**
     * Create an instance of {@link ORDERS05 .IDOC.E1EDKA1 .E1EDKA3 }
     * 
     */
    public ORDERS05 .IDOC.E1EDKA1 .E1EDKA3 createORDERS05IDOCE1EDKA1E1EDKA3() {
        return new ORDERS05 .IDOC.E1EDKA1 .E1EDKA3();
    }

}
