// SPDX-FileCopyrightText: 2017-2020 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faFemale,
  faFile,
  faFileAlt,
  faFilePdf,
  faFileSpreadsheet,
  faGavel,
  faHandHolding,
  faHiking,
  faHomeAlt,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPen,
  faPercentage,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers
} from '@fortawesome/pro-light-svg-icons'

import {
  faCaretUp as fasCaretUp,
  faCheckCircle as fasCheckCircle,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faExclamationTriangle as fasExclamationTriangle,
  faInfo as fasInfo,
  faArrowDown as fasArrowDown,
  faArrowUp as fasArrowUp
} from '@fortawesome/free-solid-svg-icons'

import { IconSet } from 'icon-set'

/* eslint-disable @typescript-eslint/no-unsafe-assignment */
const icons: IconSet = {
  faAbacus,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faAngleUp,
  faArrowUp,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faClock,
  faCoins,
  faCopy,
  faDatabase,
  faDiagnoses,
  faEnvelope,
  faEuroSign,
  faEllipsisVAlt,
  faEye,
  faEyeSlash,
  faExchange,
  faExclamation,
  faExclamationTriangle,
  faFemale,
  faFile,
  faFileAlt,
  faFilePdf,
  faFileSpreadsheet,
  faGavel,
  faHandHolding,
  faHiking,
  faHomeAlt,
  faHourglassEnd,
  faHourglassStart,
  faInfo,
  faInfoCircle,
  faLink,
  faMapMarkerAlt,
  faMeh,
  faMoneyCheck,
  faMoneyCheckEdit,
  faPen,
  faPercentage,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSync,
  faTimes,
  faTrash,
  faUndo,
  faUser,
  faUserAltSlash,
  faUserFriends,
  faUsers,
  fasCaretUp,
  fasCheckCircle,
  fasChevronDown,
  fasChevronUp,
  fasExclamationTriangle,
  fasInfo,
  fasArrowDown,
  fasArrowUp,
  farUser: faUser
}

export default icons
