// SPDX-FileCopyrightText: 2023-2025 City of Turku
//
// SPDX-License-Identifier: LGPL-2.1-or-later

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 08:53:57 AM UTC 
//


package evaka.instance.turku.payment.service;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FIDCCP02 }
     * 
     */
    public FIDCCP02 createFIDCCP02() {
        return new FIDCCP02();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC }
     * 
     */
    public FIDCCP02 .IDOC createFIDCCP02IDOC() {
        return new FIDCCP02 .IDOC();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF createFIDCCP02IDOCE1FIKPF() {
        return new FIDCCP02 .IDOC.E1FIKPF();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF.E1FISEG }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF.E1FISEG createFIDCCP02IDOCE1FIKPFE1FISEG() {
        return new FIDCCP02 .IDOC.E1FIKPF.E1FISEG();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.EDIDC40 }
     * 
     */
    public FIDCCP02 .IDOC.EDIDC40 createFIDCCP02IDOCEDIDC40() {
        return new FIDCCP02 .IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1IDOCENHANCEMENT }
     * 
     */
    public FIDCCP02 .IDOC.E1IDOCENHANCEMENT createFIDCCP02IDOCE1IDOCENHANCEMENT() {
        return new FIDCCP02 .IDOC.E1IDOCENHANCEMENT();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF.E1FISEC }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF.E1FISEC createFIDCCP02IDOCE1FIKPFE1FISEC() {
        return new FIDCCP02 .IDOC.E1FIKPF.E1FISEC();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF.E1FISET }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF.E1FISET createFIDCCP02IDOCE1FIKPFE1FISET() {
        return new FIDCCP02 .IDOC.E1FIKPF.E1FISET();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF.E1FIXWT }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF.E1FIXWT createFIDCCP02IDOCE1FIKPFE1FIXWT() {
        return new FIDCCP02 .IDOC.E1FIKPF.E1FIXWT();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF.E1FISEG.E1FISE2 }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF.E1FISEG.E1FISE2 createFIDCCP02IDOCE1FIKPFE1FISEGE1FISE2() {
        return new FIDCCP02 .IDOC.E1FIKPF.E1FISEG.E1FISE2();
    }

    /**
     * Create an instance of {@link FIDCCP02 .IDOC.E1FIKPF.E1FISEG.E1FINBU }
     * 
     */
    public FIDCCP02 .IDOC.E1FIKPF.E1FISEG.E1FINBU createFIDCCP02IDOCE1FIKPFE1FISEGE1FINBU() {
        return new FIDCCP02 .IDOC.E1FIKPF.E1FISEG.E1FINBU();
    }

}
